from argparse import Namespace

import pytest

from miles.utils.types import Sample, WeightVersionSpan, WeightVersionsPerCall
from miles.utils.weight_version import (
    MAX_ROLLOUTS_WITHOUT_PUBLISHED_WEIGHT_VERSION,
    SGLANG_DEFAULT_WEIGHT_VERSION,
    assert_samples_weight_version_sane,
    assert_weight_version_is_published,
)

SGLANG_LITERAL = "default"


def _make_args(**overrides: object) -> Namespace:
    args = Namespace(
        debug_rollout_only=False,
        debug_train_only=False,
        debug_skip_weight_update=False,
        lora_rank=0,
        lora_adapter_path=None,
    )
    for key, value in overrides.items():
        setattr(args, key, value)
    return args


def _make_sample(versions: list[str], index: int = 0) -> Sample:
    calls = [
        WeightVersionsPerCall(spans=[WeightVersionSpan(version=version, abs_start=i, abs_end=i + 1)])
        for i, version in enumerate(versions)
    ]
    return Sample(
        index=index,
        tokens=list(range(len(versions))),
        response_length=len(versions),
        weight_versions=calls,
    )


class TestAssertSamplesWeightVersionSane:
    def test_the_guarded_literal_is_the_sglang_wire_value(self):
        """sglang sends the literal 'default'; a drifted constant would let real default spans through."""
        assert SGLANG_DEFAULT_WEIGHT_VERSION == SGLANG_LITERAL

    def test_an_updated_engine_version_passes(self):
        """Tokens generated after a weight update carry a real version and must be accepted."""
        assert_samples_weight_version_sane(_make_args(), samples=[_make_sample(["3"])])

    def test_multiple_numeric_weight_versions_pass(self):
        """A trajectory spanning several weight updates carries mixed numeric versions and must be accepted."""
        assert_samples_weight_version_sane(_make_args(), samples=[_make_sample(["1", "2", "10"])])

    def test_the_sglang_default_version_fails(self):
        """Tokens generated by a never-updated engine must be rejected, not silently trained on."""
        with pytest.raises(AssertionError, match="never updated"):
            assert_samples_weight_version_sane(_make_args(), samples=[_make_sample([SGLANG_LITERAL])])

    def test_a_default_prefix_before_an_update_fails(self):
        """A request whose first tokens predate the first weight update must be caught despite later real versions."""
        with pytest.raises(AssertionError, match="never updated"):
            assert_samples_weight_version_sane(_make_args(), samples=[_make_sample([SGLANG_LITERAL, "1"])])

    def test_a_later_sample_with_a_trailing_foreign_version_fails(self):
        """Every sample and every span must be checked, not only the first sample or the first span."""
        samples = [_make_sample(["1", "2"], index=0), _make_sample(["3", SGLANG_LITERAL], index=7)]
        with pytest.raises(AssertionError, match=r"index=7 tokens \[1, 2\) were generated under weight version"):
            assert_samples_weight_version_sane(_make_args(), samples=samples)

    @pytest.mark.parametrize("version", ["mock-v0", "v3", "3.0", "-1", "", "3 "])
    def test_a_non_numeric_version_fails(self, version: str):
        """miles stamps bare numeric versions, so anything else means the weights came from outside this run."""
        with pytest.raises(AssertionError, match="not the numeric version"):
            assert_samples_weight_version_sane(_make_args(), samples=[_make_sample([version])])

    def test_a_sample_without_spans_passes(self):
        """Samples with no recorded weight versions carry nothing to validate."""
        assert_samples_weight_version_sane(_make_args(), samples=[_make_sample([])])

    @pytest.mark.parametrize(
        "overrides",
        [
            {"debug_rollout_only": True},
            {"debug_skip_weight_update": True},
            {"lora_rank": 8},
            {"lora_adapter_path": "/adapters/foo"},
        ],
    )
    def test_modes_that_never_push_weights_are_exempt(self, overrides: dict[str, object]):
        """Debug modes and LoRA legitimately serve un-updated weights, so the default version is allowed."""
        assert_samples_weight_version_sane(_make_args(**overrides), samples=[_make_sample([SGLANG_LITERAL])])


class TestAssertWeightVersionIsPublished:
    def test_a_freshly_published_version_passes(self):
        """The normal loop publishes a version every step, so the count resets to one rollout."""
        assert_weight_version_is_published(_make_args(), rollouts_since_publish=1)

    def test_a_short_gap_passes(self):
        """One late publish is tolerated so an ordinary reordering does not fail the run."""
        assert_weight_version_is_published(
            _make_args(), rollouts_since_publish=MAX_ROLLOUTS_WITHOUT_PUBLISHED_WEIGHT_VERSION
        )

    def test_a_frozen_version_fails(self):
        """A training script that never forwards the version silently disables staleness accounting."""
        with pytest.raises(AssertionError, match="set_weight_version"):
            assert_weight_version_is_published(
                _make_args(), rollouts_since_publish=MAX_ROLLOUTS_WITHOUT_PUBLISHED_WEIGHT_VERSION + 1
            )

    @pytest.mark.parametrize(
        "overrides",
        [
            {"debug_rollout_only": True},
            {"debug_train_only": True},
            {"debug_skip_weight_update": True},
            {"lora_rank": 8},
            {"lora_adapter_path": "/adapters/foo"},
        ],
    )
    def test_modes_that_never_publish_a_version_are_exempt(self, overrides: dict[str, object]):
        """These modes legitimately never push weights, so a frozen version is expected."""
        assert_weight_version_is_published(_make_args(**overrides), rollouts_since_publish=1000)
