"""Auto-generated tests for commit 257fe908: add fsdp assert back

Tests the changes introduced in branch auto/20260202221742 relative to main.
Generated by /auto-ci skill.
"""

import pytest

from miles.utils.types import Sample


class TestSampleGenerateFunctionPath:
    """Tests for the new generate_function_path field on Sample."""

    def test_default_is_none(self):
        """generate_function_path should default to None."""
        sample = Sample()
        assert sample.generate_function_path is None

    def test_set_generate_function_path(self):
        """generate_function_path can be set to a string path."""
        sample = Sample(generate_function_path="miles.rollout.custom_gen:my_func")
        assert sample.generate_function_path == "miles.rollout.custom_gen:my_func"

    def test_generate_function_path_round_trip(self):
        """generate_function_path should survive to_dict/from_dict round-trip."""
        sample = Sample(
            prompt="test prompt",
            response="test response",
            generate_function_path="module.path:func",
        )
        d = sample.to_dict()
        restored = Sample.from_dict(d)
        assert restored.generate_function_path == "module.path:func"

    def test_generate_function_path_none_round_trip(self):
        """None generate_function_path should survive to_dict/from_dict round-trip."""
        sample = Sample(prompt="test")
        d = sample.to_dict()
        restored = Sample.from_dict(d)
        assert restored.generate_function_path is None

    def test_generate_function_path_in_eval_context(self):
        """Simulates the eval_rollout_single_dataset assignment pattern."""
        sample = Sample(prompt="test")
        # This mirrors what eval_rollout_single_dataset does:
        # sample.generate_function_path = getattr(dataset_cfg, "custom_generate_function_path", None)
        custom_path = "my_module:custom_generate"
        sample.generate_function_path = custom_path
        assert sample.generate_function_path == custom_path

    def test_per_sample_priority_over_global(self):
        """Test the priority logic from generate_and_rm: per-sample path takes priority."""
        sample = Sample(generate_function_path="per_sample:func")
        global_path = "global:func"

        # This mirrors the logic in generate_and_rm:
        # custom_func_path = getattr(sample, "generate_function_path", None) or args.custom_generate_function_path
        custom_func_path = getattr(sample, "generate_function_path", None) or global_path
        assert custom_func_path == "per_sample:func"

    def test_fallback_to_global_when_sample_path_none(self):
        """When sample has no generate_function_path, falls back to global."""
        sample = Sample()
        global_path = "global:func"

        custom_func_path = getattr(sample, "generate_function_path", None) or global_path
        assert custom_func_path == "global:func"

    def test_fallback_to_none_when_both_none(self):
        """When both sample and global paths are None, result is None."""
        sample = Sample()
        global_path = None

        custom_func_path = getattr(sample, "generate_function_path", None) or global_path
        assert custom_func_path is None
