/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_dsa_train_62f0409153cad182a75c' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_dsa_train_62f0409153cad182a75c(float* __restrict__ partial, int* __restrict__ order, int* __restrict__ seg_start, int* __restrict__ seg_count, float* __restrict__ out, int dim, int keys_per_cta, int num_out);


namespace cake_host_shim_d2a54421909e5bae {

using cake_host::Optional;
using cake_host::TensorView;

class ScopedCudaDevice {
 public:
  explicit ScopedCudaDevice(int device_id) {
    cudaError_t error = cudaGetDevice(&previous_device_);
    CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
        << "cudaGetDevice failed before host-shim launch: cudaError="
        << static_cast<int>(error);
    if (previous_device_ != device_id) {
      error = cudaSetDevice(device_id);
      CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
          << "cudaSetDevice failed before host-shim launch for cuda:"
          << device_id << ": cudaError=" << static_cast<int>(error);
      restore_ = true;
    }
  }

  ScopedCudaDevice(const ScopedCudaDevice&) = delete;
  ScopedCudaDevice& operator=(const ScopedCudaDevice&) = delete;

  ~ScopedCudaDevice() noexcept {
    if (restore_) {
      (void)cudaSetDevice(previous_device_);
    }
  }

 private:
  int previous_device_ = -1;
  bool restore_ = false;
};

inline int64_t CakeDeviceMultiprocessorCount(int device_id) {
  constexpr int kMaxCachedCudaDevices = 64;
  CAKE_HOST_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "physical-SM-count cache does not cover cuda:" << device_id;
  static std::atomic<int> count_by_device[kMaxCachedCudaDevices]{};
  int cached = count_by_device[device_id].load(std::memory_order_acquire);
  if (cached > 0) return cached;

  int count = 0;
  cudaError_t error = cudaDeviceGetAttribute(
      &count, cudaDevAttrMultiProcessorCount, device_id);
  CAKE_HOST_CHECK(error == cudaSuccess && count > 0, RuntimeError)
      << "querying multiProcessorCount failed for cuda:" << device_id
      << ": cudaError=" << static_cast<int>(error) << ", count=" << count;
  // Concurrent first launches may repeat the immutable device query, but all
  // publication is atomic and every later hot-path lookup is one acquire load.
  count_by_device[device_id].store(count, std::memory_order_release);
  return count;
}

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  CAKE_HOST_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(
    const TensorView& t,
    const TensorView& reference,
    const char* name,
    const char* reference_name) {
  CAKE_HOST_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id
      << " versus cuda:" << reference.device().device_id;
}

inline void CheckCurrentCudaDevice(
    const TensorView& reference,
    const char* reference_name) {
  int current_device = -1;
  cudaError_t error = cudaGetDevice(&current_device);
  CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
      << "cudaGetDevice failed while validating " << reference_name
      << ": cudaError=" << static_cast<int>(error);
  CAKE_HOST_CHECK(current_device == reference.device().device_id, ValueError)
      << "current CUDA device must match " << reference_name
      << ": current=cuda:" << current_device
      << ", tensor=cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  CAKE_HOST_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  CAKE_HOST_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  CAKE_HOST_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  CAKE_HOST_CHECK(step > 0, ValueError)
      << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      CAKE_HOST_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis)
          << ", expected " << expected;
    }
  }
}

void Run(TensorView arg_partial, TensorView arg_order, TensorView arg_seg_start, TensorView arg_seg_count, TensorView arg_out, int64_t arg_dim, int64_t arg_keys_per_cta, int64_t arg_num_out, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_partial.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_partial, "partial");
  CheckDtype(arg_partial, "partial", 2, 32, 1);
  CheckContiguous(arg_partial, "partial");
  CheckCudaTensor(arg_order, "order");
  CheckDtype(arg_order, "order", 0, 32, 1);
  CheckContiguous(arg_order, "order");
  CheckCudaTensor(arg_seg_start, "seg_start");
  CheckDtype(arg_seg_start, "seg_start", 0, 32, 1);
  CheckContiguous(arg_seg_start, "seg_start");
  CheckCudaTensor(arg_seg_count, "seg_count");
  CheckDtype(arg_seg_count, "seg_count", 0, 32, 1);
  CheckContiguous(arg_seg_count, "seg_count");
  CheckCudaTensor(arg_out, "out");
  CheckDtype(arg_out, "out", 2, 32, 1);
  CheckContiguous(arg_out, "out");
  CAKE_HOST_CHECK(arg_dim >= -2147483648LL && arg_dim <= 2147483647LL, ValueError)
      << "scalar 'dim' value " << arg_dim
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_keys_per_cta >= -2147483648LL && arg_keys_per_cta <= 2147483647LL, ValueError)
      << "scalar 'keys_per_cta' value " << arg_keys_per_cta
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_out >= -2147483648LL && arg_num_out <= 2147483647LL, ValueError)
      << "scalar 'num_out' value " << arg_num_out
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_order, arg_partial, "order", "partial");
  CheckSameCudaDevice(arg_seg_start, arg_partial, "seg_start", "partial");
  CheckSameCudaDevice(arg_seg_count, arg_partial, "seg_count", "partial");
  CheckSameCudaDevice(arg_out, arg_partial, "out", "partial");
  CheckCurrentCudaDevice(arg_partial, "partial");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  float* p_partial = static_cast<float*>(arg_partial.data_ptr());
  int* p_order = static_cast<int*>(arg_order.data_ptr());
  int* p_seg_start = static_cast<int*>(arg_seg_start.data_ptr());
  int* p_seg_count = static_cast<int*>(arg_seg_count.data_ptr());
  float* p_out = static_cast<float*>(arg_out.data_ptr());
  int32_t v_dim = (int32_t)arg_dim;
  int32_t v_keys_per_cta = (int32_t)arg_keys_per_cta;
  int32_t v_num_out = (int32_t)arg_num_out;
  void* kargs[] = {&p_partial, &p_order, &p_seg_start, &p_seg_count, &p_out, &v_dim, &v_keys_per_cta, &v_num_out};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 0u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_dsa_train_62f0409153cad182a75c), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_dsa_train_62f0409153cad182a75c failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_d2a54421909e5bae

CAKE_HOST_EXPORT(run, cake_host_shim_d2a54421909e5bae::Run);
