+### Steps per rollout
+
+`--max-weight-staleness` is not the only source of off-policyness. A drained batch is
+split into `rollout_batch_size * n_samples_per_prompt // global_batch_size` optimizer
+steps, so with more than one step the second and later steps update weights that have
+already moved away from the policy that generated the data. That per-batch gap stacks on
+top of the inter-batch gap the staleness filter allows, and the two are configured
+independently.
+
+The invariant fully async assumes is one optimizer step per drain. Two ways to get it:
+set `--num-steps-per-rollout 1`, or pass `--use-dynamic-global-batch-size`, which sizes
+the global batch to the samples actually collected and therefore always lands on a single
+step. Miles warns at startup when `--max-weight-staleness` is set and the configuration
+implies more than one step, but it does not error: multi-step is valid for overlapped
+async recipes that account for the compounded off-policyness themselves.
+
 ## Evaluation
 
 Fully async rollout changes one thing about eval: generation is always in flight, so an
diff --git a/miles/utils/arguments.py b/miles/utils/arguments.py
index 3f5fcd0..6f97d96 100644
--- a/miles/utils/arguments.py
+++ b/miles/utils/arguments.py
@@ -2399,7 +2399,13 @@ def get_miles_extra_args_provider(add_custom_arguments=None):
                 "--use-dynamic-global-batch-size",
                 action="store_true",
                 default=False,
-                help="enable dynamic global batch size, disable trim samples in rollout buffer when converting samples to train data",
+                help=(
+                    "Size the global batch to the samples actually collected instead of trimming "
+                    "the rollout buffer down to a multiple of --global-batch-size. This avoids "
+                    "discarding samples when the collected count is variable (dynamic sampling, "
+                    "oversampling recycle), and in fully async mode it pins the drained batch to "
+                    "exactly one optimizer step."
+                ),
             )
             return parser
 
@@ -3414,6 +3420,30 @@ def miles_validate_args(args):
             )
         args.global_batch_size = global_batch_size
 
+    # Staleness-based async already introduces an inter-batch weight-version gap: the drained
+    # batch was generated by a policy up to `max_weight_staleness` versions behind. Splitting
+    # that batch into more than one optimizer step stacks per-batch off-policyness on top of
+    # the gap, because steps 2..N are applied to weights that have already moved away from the
+    # policy that produced the data. This is legitimate for some overlapped-async recipes, so
+    # warn instead of erroring. `--use-dynamic-global-batch-size` resizes gbs to the drained
+    # sample count and therefore always yields exactly one step, so it is exempt.
+    if args.max_weight_staleness is not None and not args.use_dynamic_global_batch_size:
+        if args.num_steps_per_rollout is not None:
+            effective_steps_per_rollout = args.num_steps_per_rollout
+        elif args.global_batch_size:
+            effective_steps_per_rollout = args.rollout_batch_size * args.n_samples_per_prompt // args.global_batch_size
+        else:
+            effective_steps_per_rollout = None
+        if effective_steps_per_rollout is not None and effective_steps_per_rollout > 1:
+            logger.warning(
+                f"num_steps_per_rollout={effective_steps_per_rollout} (>1) is combined with "
+                f"max_weight_staleness={args.max_weight_staleness}. Each rollout batch is already "
+                "off-policy by up to that many weight versions, and splitting it into multiple "
+                "optimizer steps compounds this with per-batch off-policyness. Set "
+                "--num-steps-per-rollout 1, or --use-dynamic-global-batch-size to size the "
+                "global batch to the drained batch, unless this is intended."
+            )
+
     # Multi-LoRA adapters carry their own n_samples_per_prompt; the per-group
     # normalization path already skips std for singleton groups.
     if args.n_samples_per_prompt == 1 and not args.multi_lora:
diff --git a/tests/fast/utils/test_arguments.py b/tests/fast/utils/test_arguments.py
index 9082f9c..e701585 100644
--- a/tests/fast/utils/test_arguments.py
+++ b/tests/fast/utils/test_arguments.py
@@ -286,6 +286,51 @@ def test_dynamic_global_batch_size_requires_dynamic_batch_size():
         miles_validate_args(args)
 
 
+class TestMultiStepStalenessWarning:
+    WARNING_PREFIX = "num_steps_per_rollout="
+
+    def _validate(self, caplog, extra):
+        parser = argparse.ArgumentParser()
+        get_miles_extra_args_provider()(parser)
+        args = parser.parse_args(extra + ["--num-rollout", "1"] + REQUIRED_ARGS)
+
+        with caplog.at_level(logging.WARNING, logger="miles.utils.arguments"):
+            miles_validate_args(args)
+
+        return [record for record in caplog.records if record.getMessage().startswith(self.WARNING_PREFIX)]
+
+    @pytest.mark.parametrize(
+        "extra, expect_warning",
+        [
+            # Multi-step training on top of staleness-based async compounds off-policyness.
+            (["--max-weight-staleness", "2", "--num-steps-per-rollout", "4"], True),
+            # Same, but the step count is implied by an explicit global batch size.
+            (["--max-weight-staleness", "2", "--n-samples-per-prompt", "4", "--global-batch-size", "64"], True),
+            # One optimizer step per rollout is the safe configuration.
+            (["--max-weight-staleness", "2", "--num-steps-per-rollout", "1"], False),
+            # Staleness filtering disabled: multi-step is the ordinary sync behaviour.
+            (["--num-steps-per-rollout", "4"], False),
+        ],
+    )
+    def test_warns_only_when_multi_step_meets_staleness(self, caplog, extra, expect_warning):
+        assert len(self._validate(caplog, extra)) == int(expect_warning)
+
+    def test_dynamic_global_batch_size_is_exempt(self, caplog):
+        # --use-dynamic-global-batch-size resizes gbs to the drained batch, so the run always
+        # takes exactly one optimizer step regardless of --num-steps-per-rollout.
+        extra = [
+            "--max-weight-staleness",
+            "2",
+            "--num-steps-per-rollout",
+            "4",
+            "--use-dynamic-global-batch-size",
+            "--use-dynamic-batch-size",
+            "--max-tokens-per-gpu",
+            "8192",
+        ]
+        assert self._validate(caplog, extra) == []
+
+
"""Configuration dataclasses for SGLang engine deployment."""

import dataclasses
import logging

import yaml

logger = logging.getLogger(__name__)


@dataclasses.dataclass
class ServerGroupConfig:
    """Configuration for a single server group.

    Attributes:
        worker_type: One of "regular", "prefill", "decode", or "placeholder".
                     "placeholder" reserves GPU slots without creating engines.
        num_gpus: Total number of GPUs for this group.
        num_gpus_per_engine: GPUs per engine for this group.  Overrides the
                             model-level or global ``--rollout-num-gpus-per-engine``.
        overrides: Optional dict of SGLang ``ServerArgs`` field overrides.
                   These are applied on top of the base CLI ``--sglang-*``
                   arguments in ``_compute_server_args``.
    """

    worker_type: str
    num_gpus: int
    num_gpus_per_engine: int | None = None
    overrides: dict = dataclasses.field(default_factory=dict)

    def __post_init__(self):
        valid_types = {"regular", "prefill", "decode", "placeholder"}
        assert (
            self.worker_type in valid_types
        ), f"Invalid worker_type '{self.worker_type}', must be one of {valid_types}"
        assert self.num_gpus > 0, f"num_gpus must be > 0, got {self.num_gpus}"


@dataclasses.dataclass
class ModelConfig:
    """Configuration for a single model deployment.

    Attributes:
        name: Unique name for this model (e.g. "actor", "reward").
        model_path: HF checkpoint path.  Falls back to ``args.hf_checkpoint``.
        num_gpus_per_engine: Default GPUs per engine for all groups in this
                             model.  Individual groups can override.
        server_groups: Server group configurations for this model.
        update_weights: Whether this model receives weight updates from
                        training.  Set to ``False`` for frozen models
                        (reference, reward, etc.).  When ``None`` (default),
                        automatically inferred in ``resolve()``: ``True`` if
                        model_path matches ``args.hf_checkpoint``, ``False``
                        otherwise.
    """

    name: str
    model_path: str | None = None
    num_gpus_per_engine: int | None = None
    server_groups: list[ServerGroupConfig] = dataclasses.field(default_factory=list)
    update_weights: bool | None = None

    def resolve(self, args) -> None:
        """Resolve per-group defaults from model-level then args-level values."""
        default_gpus_per_engine = self.num_gpus_per_engine or args.rollout_num_gpus_per_engine
        default_model_path = self.model_path or args.hf_checkpoint
        for g in self.server_groups:
            if g.num_gpus_per_engine is None:
                g.num_gpus_per_engine = default_gpus_per_engine
            if "model_path" not in g.overrides:
                g.overrides["model_path"] = default_model_path

        if self.server_groups:
            model_paths = {g.overrides["model_path"] for g in self.server_groups}
            assert len(model_paths) == 1, (
                f"Model '{self.name}' has server groups with different model_path values: "
                f"{model_paths}. All server groups within a model must use the same model_path."
            )
            effective_model_path = model_paths.pop()
        else:
            effective_model_path = default_model_path

        if self.update_weights is None:
            if effective_model_path != args.hf_checkpoint:
                logger.warning(
                    f"Model '{self.name}' uses model_path='{effective_model_path}' which differs "
                    f"from hf_checkpoint='{args.hf_checkpoint}'. Defaulting update_weights to False. "
                    f"Set update_weights explicitly in the config to suppress this warning."
                )
                self.update_weights = False
            else:
                self.update_weights = True

    @property
    def has_pd_disaggregation(self) -> bool:
        return any(g.worker_type in ("prefill", "decode") for g in self.server_groups)

    @property
    def total_num_gpus(self) -> int:
        return sum(g.num_gpus for g in self.server_groups)


@dataclasses.dataclass
class SglangConfig:
    """Configuration for SGLang engine deployment.

    Loaded from ``--sglang-config`` YAML file.

    **Config format**::

        sglang:
          - name: actor
            model_path: /path/to/actor
            update_weights: true          # receives training weight updates (default)
            num_gpus_per_engine: 2
            server_groups:
              - worker_type: prefill
                num_gpus: 4
                num_gpus_per_engine: 2
              - worker_type: decode
                num_gpus: 8
                num_gpus_per_engine: 4
          - name: ref
            model_path: /path/to/ref
            update_weights: false          # frozen, no weight updates
            server_groups:
              - worker_type: regular
                num_gpus: 4

    Each model gets its own router.  ``placeholder`` groups reserve GPU
    slots without creating engines.  ``overrides`` are ``ServerArgs``
    field names applied on top of the base ``--sglang-*`` CLI args.

    Set ``update_weights: false`` for frozen models (reference, reward,
    etc.) that should not receive weight updates from training.

    .. note::

       ``engine_groups`` is accepted as a backward-compatible alias for
       ``server_groups`` in the YAML config.
    """

    models: list[ModelConfig]

    @staticmethod
    def from_yaml(path: str) -> "SglangConfig":
        with open(path) as f:
            data = yaml.safe_load(f)

        assert "sglang" in data, (
            f"sglang config must have a 'sglang' key, got {list(data.keys())}. "
            f"Wrap your server_groups inside a model entry under 'sglang'."
        )
        models = []
        for m in data["sglang"]:
            raw_groups = m.get("server_groups") or m.get("engine_groups") or []
            groups = [ServerGroupConfig(**g) for g in raw_groups]
            models.append(
                ModelConfig(
                    name=m["name"],
                    model_path=m.get("model_path"),
                    num_gpus_per_engine=m.get("num_gpus_per_engine"),
                    server_groups=groups,
                    update_weights=m.get("update_weights"),
                )
            )
        return SglangConfig(models=models)

    @staticmethod
    def from_prefill_num_servers(args) -> "SglangConfig":
        """Build a config equivalent to the legacy --prefill-num-servers flag."""
        total_gpus = args.rollout_num_gpus
        prefill_gpus = args.prefill_num_servers * args.rollout_num_gpus_per_engine
        decode_gpus = total_gpus - prefill_gpus
        assert decode_gpus > 0, f"No decode GPUs: total {total_gpus}, prefill {prefill_gpus}"
        return SglangConfig(
            models=[
                ModelConfig(
                    name="default",
                    server_groups=[
                        ServerGroupConfig(worker_type="prefill", num_gpus=prefill_gpus),
                        ServerGroupConfig(worker_type="decode", num_gpus=decode_gpus),
                    ],
                )
            ]
        )

    @property
    def has_pd_disaggregation(self) -> bool:
        return any(m.has_pd_disaggregation for m in self.models)

    @property
    def total_num_gpus(self) -> int:
        return sum(m.total_num_gpus for m in self.models)
