name: 'Setup Miles'
description: 'Cleanup stale processes, resolve dependency refs, and install Miles with its dependencies'

inputs:
  pr_body:
    description: 'PR body text for parsing dependency ref overrides (ci-megatron-pr: / ci-sglang-pr:)'
    required: false
    default: ''
  megatron_pr:
    description: 'Megatron-LM branch/commit override from workflow_dispatch'
    required: false
    default: ''
  sglang_pr:
    description: 'SGLang branch/commit override from workflow_dispatch'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cleanup stale processes
      shell: bash
      run: |
        pkill -9 -f 'ray::' 2>/dev/null || true
        pkill -9 -f raylet 2>/dev/null || true
        pkill -9 -f gcs_server 2>/dev/null || true
        pkill -9 -f 'ray-dashboard' 2>/dev/null || true
        pkill -9 sglang 2>/dev/null || true
        ray stop --force 2>/dev/null || true
        rm -rf /tmp/ray/* 2>/dev/null || true
        sleep 3

    - name: Resolve dependency refs and install
      shell: bash
      env:
        PR_BODY: ${{ inputs.pr_body }}
        INPUT_MEGATRON_PR: ${{ inputs.megatron_pr }}
        INPUT_SGLANG_PR: ${{ inputs.sglang_pr }}
      run: |
        # Priority: workflow_dispatch input > PR description > default
        MEGATRON_PR="${INPUT_MEGATRON_PR}"
        SGLANG_PR="${INPUT_SGLANG_PR}"

        if [ -n "$PR_BODY" ]; then
          PR_MEGATRON_PR=$(echo "$PR_BODY" | grep -oP '(?<=ci-megatron-pr:\s)\S+' || true)
          PR_SGLANG_PR=$(echo "$PR_BODY" | grep -oP '(?<=ci-sglang-pr:\s)\S+' || true)
          [ -z "$MEGATRON_PR" ] && [ -n "$PR_MEGATRON_PR" ] && MEGATRON_PR="$PR_MEGATRON_PR"
          [ -z "$SGLANG_PR" ] && [ -n "$PR_SGLANG_PR" ] && SGLANG_PR="$PR_SGLANG_PR"
        fi

        [ -z "$MEGATRON_PR" ] && MEGATRON_PR="miles-main"
        [ -z "$SGLANG_PR" ] && SGLANG_PR="sglang-miles"

        # Convert "#N" PR syntax to git fetch ref: "pull/N/head"
        resolve_fetch_ref() {
          local ref="$1"
          if [[ "$ref" =~ ^#([0-9]+)$ ]]; then
            echo "pull/${BASH_REMATCH[1]}/head"
          else
            echo "$ref"
          fi
        }
        MEGATRON_FETCH=$(resolve_fetch_ref "$MEGATRON_PR")
        SGLANG_FETCH=$(resolve_fetch_ref "$SGLANG_PR")

        echo "Resolved: megatron=$MEGATRON_PR -> fetch=$MEGATRON_FETCH, sglang=$SGLANG_PR -> fetch=$SGLANG_FETCH"

        cd /sgl-workspace/sglang && git reset --hard HEAD && git clean -fd && git fetch origin "$SGLANG_FETCH" && git checkout -f FETCH_HEAD && git log --oneline -1 && pip install -e python --no-deps --break-system-packages
        cd /root/Megatron-LM && git reset --hard HEAD && git clean -fd && git fetch origin "$MEGATRON_FETCH" && git checkout -f FETCH_HEAD && git log --oneline -1 && pip install -e . --no-deps --break-system-packages
        cd $GITHUB_WORKSPACE && pip install -e . --no-deps --break-system-packages
