/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_kda_chunk_train_44efcf0c120ed5a2139b' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_kda_chunk_train_44efcf0c120ed5a2139b(float* __restrict__ dA_part, float* __restrict__ dbias_part, float* __restrict__ dA_log, float* __restrict__ dt_bias_grad, int num_chunks, int num_heads);


namespace cake_host_shim_a5a99af4991db27f {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_dA_part, TensorView arg_dbias_part, TensorView arg_dA_log, TensorView arg_dt_bias_grad, int64_t arg_num_chunks, int64_t arg_num_heads, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_dA_part.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_dA_part, "dA_part");
  CheckDtype(arg_dA_part, "dA_part", 2, 32, 1);
  CheckContiguous(arg_dA_part, "dA_part");
  CheckCudaTensor(arg_dbias_part, "dbias_part");
  CheckDtype(arg_dbias_part, "dbias_part", 2, 32, 1);
  CheckContiguous(arg_dbias_part, "dbias_part");
  CheckCudaTensor(arg_dA_log, "dA_log");
  CheckDtype(arg_dA_log, "dA_log", 2, 32, 1);
  CheckContiguous(arg_dA_log, "dA_log");
  CheckCudaTensor(arg_dt_bias_grad, "dt_bias_grad");
  CheckDtype(arg_dt_bias_grad, "dt_bias_grad", 2, 32, 1);
  CheckContiguous(arg_dt_bias_grad, "dt_bias_grad");
  CAKE_HOST_CHECK(arg_num_chunks >= -2147483648LL && arg_num_chunks <= 2147483647LL, ValueError)
      << "scalar 'num_chunks' value " << arg_num_chunks
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_dbias_part, arg_dA_part, "dbias_part", "dA_part");
  CheckSameCudaDevice(arg_dA_log, arg_dA_part, "dA_log", "dA_part");
  CheckSameCudaDevice(arg_dt_bias_grad, arg_dA_part, "dt_bias_grad", "dA_part");
  CheckCurrentCudaDevice(arg_dA_part, "dA_part");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  float* p_dA_part = static_cast<float*>(arg_dA_part.data_ptr());
  float* p_dbias_part = static_cast<float*>(arg_dbias_part.data_ptr());
  float* p_dA_log = static_cast<float*>(arg_dA_log.data_ptr());
  float* p_dt_bias_grad = static_cast<float*>(arg_dt_bias_grad.data_ptr());
  int32_t v_num_chunks = (int32_t)arg_num_chunks;
  int32_t v_num_heads = (int32_t)arg_num_heads;
  void* kargs[] = {&p_dA_part, &p_dbias_part, &p_dA_log, &p_dt_bias_grad, &v_num_chunks, &v_num_heads};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 128u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_kda_chunk_train_44efcf0c120ed5a2139b), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_kda_chunk_train_44efcf0c120ed5a2139b failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_a5a99af4991db27f

CAKE_HOST_STAGE(finalize, cake_host_shim_a5a99af4991db27f::Run);
