/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_kda_chunk_train_a088c4a8ae7c7196a093' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_kda_chunk_train_a088c4a8ae7c7196a093(float* __restrict__ dq_intra, float* __restrict__ dk_intra, __nv_bfloat16* __restrict__ q_norm, __nv_bfloat16* __restrict__ k_norm, float* __restrict__ q_rstd, float* __restrict__ k_rstd, int* __restrict__ chunk_bos, int* __restrict__ chunk_len, __nv_bfloat16* __restrict__ dq_out, __nv_bfloat16* __restrict__ dk_out, int num_qk_heads, int num_v_heads, int group);


namespace cake_host_shim_a8c2c2eb4c29b2f2 {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_dq_intra, TensorView arg_dk_intra, TensorView arg_q_norm, TensorView arg_k_norm, TensorView arg_q_rstd, TensorView arg_k_rstd, TensorView arg_chunk_bos, TensorView arg_chunk_len, TensorView arg_dq_out, TensorView arg_dk_out, int64_t arg_num_qk_heads, int64_t arg_num_v_heads, int64_t arg_group, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_dq_intra.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_dq_intra, "dq_intra");
  CheckDtype(arg_dq_intra, "dq_intra", 2, 32, 1);
  CheckContiguous(arg_dq_intra, "dq_intra");
  CheckCudaTensor(arg_dk_intra, "dk_intra");
  CheckDtype(arg_dk_intra, "dk_intra", 2, 32, 1);
  CheckContiguous(arg_dk_intra, "dk_intra");
  CheckCudaTensor(arg_q_norm, "q_norm");
  CheckDtype(arg_q_norm, "q_norm", 4, 16, 1);
  CheckContiguous(arg_q_norm, "q_norm");
  CheckCudaTensor(arg_k_norm, "k_norm");
  CheckDtype(arg_k_norm, "k_norm", 4, 16, 1);
  CheckContiguous(arg_k_norm, "k_norm");
  CheckCudaTensor(arg_q_rstd, "q_rstd");
  CheckDtype(arg_q_rstd, "q_rstd", 2, 32, 1);
  CheckContiguous(arg_q_rstd, "q_rstd");
  CheckCudaTensor(arg_k_rstd, "k_rstd");
  CheckDtype(arg_k_rstd, "k_rstd", 2, 32, 1);
  CheckContiguous(arg_k_rstd, "k_rstd");
  CheckCudaTensor(arg_chunk_bos, "chunk_bos");
  CheckDtype(arg_chunk_bos, "chunk_bos", 0, 32, 1);
  CheckContiguous(arg_chunk_bos, "chunk_bos");
  CheckCudaTensor(arg_chunk_len, "chunk_len");
  CheckDtype(arg_chunk_len, "chunk_len", 0, 32, 1);
  CheckContiguous(arg_chunk_len, "chunk_len");
  CheckCudaTensor(arg_dq_out, "dq_out");
  CheckDtype(arg_dq_out, "dq_out", 4, 16, 1);
  CheckContiguous(arg_dq_out, "dq_out");
  CheckCudaTensor(arg_dk_out, "dk_out");
  CheckDtype(arg_dk_out, "dk_out", 4, 16, 1);
  CheckContiguous(arg_dk_out, "dk_out");
  CAKE_HOST_CHECK(arg_num_qk_heads >= -2147483648LL && arg_num_qk_heads <= 2147483647LL, ValueError)
      << "scalar 'num_qk_heads' value " << arg_num_qk_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_v_heads >= -2147483648LL && arg_num_v_heads <= 2147483647LL, ValueError)
      << "scalar 'num_v_heads' value " << arg_num_v_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_group >= -2147483648LL && arg_group <= 2147483647LL, ValueError)
      << "scalar 'group' value " << arg_group
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_dk_intra, arg_dq_intra, "dk_intra", "dq_intra");
  CheckSameCudaDevice(arg_q_norm, arg_dq_intra, "q_norm", "dq_intra");
  CheckSameCudaDevice(arg_k_norm, arg_dq_intra, "k_norm", "dq_intra");
  CheckSameCudaDevice(arg_q_rstd, arg_dq_intra, "q_rstd", "dq_intra");
  CheckSameCudaDevice(arg_k_rstd, arg_dq_intra, "k_rstd", "dq_intra");
  CheckSameCudaDevice(arg_chunk_bos, arg_dq_intra, "chunk_bos", "dq_intra");
  CheckSameCudaDevice(arg_chunk_len, arg_dq_intra, "chunk_len", "dq_intra");
  CheckSameCudaDevice(arg_dq_out, arg_dq_intra, "dq_out", "dq_intra");
  CheckSameCudaDevice(arg_dk_out, arg_dq_intra, "dk_out", "dq_intra");
  CheckCurrentCudaDevice(arg_dq_intra, "dq_intra");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  float* p_dq_intra = static_cast<float*>(arg_dq_intra.data_ptr());
  float* p_dk_intra = static_cast<float*>(arg_dk_intra.data_ptr());
  __nv_bfloat16* p_q_norm = static_cast<__nv_bfloat16*>(arg_q_norm.data_ptr());
  __nv_bfloat16* p_k_norm = static_cast<__nv_bfloat16*>(arg_k_norm.data_ptr());
  float* p_q_rstd = static_cast<float*>(arg_q_rstd.data_ptr());
  float* p_k_rstd = static_cast<float*>(arg_k_rstd.data_ptr());
  int* p_chunk_bos = static_cast<int*>(arg_chunk_bos.data_ptr());
  int* p_chunk_len = static_cast<int*>(arg_chunk_len.data_ptr());
  __nv_bfloat16* p_dq_out = static_cast<__nv_bfloat16*>(arg_dq_out.data_ptr());
  __nv_bfloat16* p_dk_out = static_cast<__nv_bfloat16*>(arg_dk_out.data_ptr());
  int32_t v_num_qk_heads = (int32_t)arg_num_qk_heads;
  int32_t v_num_v_heads = (int32_t)arg_num_v_heads;
  int32_t v_group = (int32_t)arg_group;
  void* kargs[] = {&p_dq_intra, &p_dk_intra, &p_q_norm, &p_k_norm, &p_q_rstd, &p_k_rstd, &p_chunk_bos, &p_chunk_len, &p_dq_out, &p_dk_out, &v_num_qk_heads, &v_num_v_heads, &v_group};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(256u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 0u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_kda_chunk_train_a088c4a8ae7c7196a093), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_kda_chunk_train_a088c4a8ae7c7196a093 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_a8c2c2eb4c29b2f2

CAKE_HOST_STAGE(qk_epilogue, cake_host_shim_a8c2c2eb4c29b2f2::Run);
