/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_kda_chunk_train_61eaa8af22292a7ef117' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

struct CakeTensorMap;
extern "C" __global__ void kernel_cake_kda_chunk_train_61eaa8af22292a7ef117(CakeTensorMap const* akk_tma, CakeTensorMap const* vb_tma, CakeTensorMap const* kb_tma, __nv_bfloat16* __restrict__ u_out, __nv_bfloat16* __restrict__ w_out, int num_heads);


namespace cake_host_shim_0de6f99a5ec28a53 {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

// Caller-owned storage is mutable scratch, including when its address and
// underlying CUDA allocation stay unchanged. Refresh all descriptors on the
// launch stream every time; allocation identity cannot establish their contents.
// By-value kernel parameters make the upload independent of host-buffer lifetime
// and record the descriptor bytes in CUDA Graphs for every replay.
template <size_t N>
struct CallerTmaDescriptorBatch {
  uint4 words[N * sizeof(CUtensorMap) / sizeof(uint4)];
};

template <size_t N>
__global__ void UploadCallerTmaDescriptors(
    uint4* workspace, CallerTmaDescriptorBatch<N> descriptors) {
  for (size_t i = threadIdx.x;
       i < N * sizeof(CUtensorMap) / sizeof(uint4); i += blockDim.x) {
    workspace[i] = descriptors.words[i];
  }
  // Generated pointer-ABI consumers acquire the tensor-map proxy before use.
  asm volatile("fence.proxy.tensormap::generic.release.sys;" ::: "memory");
}

template <size_t N>
static inline void UploadCallerTmaWorkspace(
    void* workspace, const CUtensorMap (&maps)[N], cudaStream_t stream) {
  CallerTmaDescriptorBatch<N> descriptors;
  static_assert(sizeof(descriptors) == sizeof(maps), "tensor-map batch ABI");
  std::memcpy(&descriptors, maps, sizeof(maps));
  void* args[] = {&workspace, &descriptors};
  cudaError_t result = cudaLaunchKernel(
      reinterpret_cast<const void*>(UploadCallerTmaDescriptors<N>),
      dim3(1), dim3(32), args, 0, stream);
  CAKE_HOST_CHECK(result == cudaSuccess, RuntimeError)
      << "uploading caller-owned TMA descriptors failed: "
      << cudaGetErrorString(result);
}

static inline void* CallerTmaWorkspaceSlot(
    const cake_host::TensorView& workspace,
    size_t slot) {
  const uintptr_t base = reinterpret_cast<uintptr_t>(workspace.data_ptr());
  const uintptr_t address = base + slot * sizeof(CUtensorMap);
  return reinterpret_cast<void*>(address);
}

// 3D TMA descriptor for buffer 'akk_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_akk_tma(const TensorView& t) {
  CAKE_HOST_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'akk_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  CAKE_HOST_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'akk_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  CAKE_HOST_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'akk_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  CAKE_HOST_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'akk_tma' resolved a non-positive global dim";
  CAKE_HOST_CHECK(64u <= global_dim[0] && 1u <= global_dim[1] && 64u <= global_dim[2], ValueError)
      << "TMA box (64, 1, 64) exceeds resolved global dims for 'akk_tma'";
  int64_t carrier_stride_0 = d1;
  CAKE_HOST_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'akk_tma' resolved global stride 1 negative";
  CAKE_HOST_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'akk_tma' resolved global stride 1 zero while global dimension 1 is not 1";
  CAKE_HOST_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'akk_tma' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = (d1 * d2);
  CAKE_HOST_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'akk_tma' resolved global stride 2 negative";
  CAKE_HOST_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'akk_tma' resolved global stride 2 zero while global dimension 2 is not 1";
  CAKE_HOST_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'akk_tma' resolved global stride 2 to a non-whole-byte offset";
  uint64_t global_strides[2] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
  };
  uint32_t box_dim[3] = {64u, 1u, 64u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  CAKE_HOST_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'akk_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 3D TMA descriptor for buffer 'vb_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_vb_tma(const TensorView& t) {
  CAKE_HOST_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'vb_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  CAKE_HOST_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'vb_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  CAKE_HOST_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'vb_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  CAKE_HOST_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'vb_tma' resolved a non-positive global dim";
  CAKE_HOST_CHECK(64u <= global_dim[0] && 1u <= global_dim[1] && 128u <= global_dim[2], ValueError)
      << "TMA box (64, 1, 128) exceeds resolved global dims for 'vb_tma'";
  int64_t carrier_stride_0 = d1;
  CAKE_HOST_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'vb_tma' resolved global stride 1 negative";
  CAKE_HOST_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'vb_tma' resolved global stride 1 zero while global dimension 1 is not 1";
  CAKE_HOST_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'vb_tma' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = (d1 * d2);
  CAKE_HOST_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'vb_tma' resolved global stride 2 negative";
  CAKE_HOST_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'vb_tma' resolved global stride 2 zero while global dimension 2 is not 1";
  CAKE_HOST_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'vb_tma' resolved global stride 2 to a non-whole-byte offset";
  uint64_t global_strides[2] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
  };
  uint32_t box_dim[3] = {64u, 1u, 128u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  CAKE_HOST_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'vb_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 3D TMA descriptor for buffer 'kb_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_kb_tma(const TensorView& t) {
  CAKE_HOST_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'kb_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  CAKE_HOST_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'kb_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  CAKE_HOST_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'kb_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  CAKE_HOST_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'kb_tma' resolved a non-positive global dim";
  CAKE_HOST_CHECK(64u <= global_dim[0] && 1u <= global_dim[1] && 128u <= global_dim[2], ValueError)
      << "TMA box (64, 1, 128) exceeds resolved global dims for 'kb_tma'";
  int64_t carrier_stride_0 = d1;
  CAKE_HOST_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'kb_tma' resolved global stride 1 negative";
  CAKE_HOST_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'kb_tma' resolved global stride 1 zero while global dimension 1 is not 1";
  CAKE_HOST_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'kb_tma' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = (d1 * d2);
  CAKE_HOST_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'kb_tma' resolved global stride 2 negative";
  CAKE_HOST_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'kb_tma' resolved global stride 2 zero while global dimension 2 is not 1";
  CAKE_HOST_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'kb_tma' resolved global stride 2 to a non-whole-byte offset";
  uint64_t global_strides[2] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
  };
  uint32_t box_dim[3] = {64u, 1u, 128u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  CAKE_HOST_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'kb_tma') failed: CUresult=" << (int)r;
  return tm;
}

void Run(TensorView arg_akk_tma, TensorView arg_vb_tma, TensorView arg_kb_tma, TensorView arg_u_out, TensorView arg_w_out, int64_t arg_num_heads, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_akk_tma.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_akk_tma, "akk_tma");
  CheckDtype(arg_akk_tma, "akk_tma", 4, 16, 1);
  CheckContiguous(arg_akk_tma, "akk_tma");
  CheckCudaTensor(arg_vb_tma, "vb_tma");
  CheckDtype(arg_vb_tma, "vb_tma", 4, 16, 1);
  CheckContiguous(arg_vb_tma, "vb_tma");
  CheckCudaTensor(arg_kb_tma, "kb_tma");
  CheckDtype(arg_kb_tma, "kb_tma", 4, 16, 1);
  CheckContiguous(arg_kb_tma, "kb_tma");
  CheckCudaTensor(arg_u_out, "u_out");
  CheckDtype(arg_u_out, "u_out", 4, 16, 1);
  CheckContiguous(arg_u_out, "u_out");
  CheckCudaTensor(arg_w_out, "w_out");
  CheckDtype(arg_w_out, "w_out", 4, 16, 1);
  CheckContiguous(arg_w_out, "w_out");
  CAKE_HOST_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_vb_tma, arg_akk_tma, "vb_tma", "akk_tma");
  CheckSameCudaDevice(arg_kb_tma, arg_akk_tma, "kb_tma", "akk_tma");
  CheckSameCudaDevice(arg_u_out, arg_akk_tma, "u_out", "akk_tma");
  CheckSameCudaDevice(arg_w_out, arg_akk_tma, "w_out", "akk_tma");
  CheckCurrentCudaDevice(arg_akk_tma, "akk_tma");
  CheckCudaTensor(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckSameCudaDevice(arg_tma_descriptor_workspace, arg_akk_tma, "tma_descriptor_workspace", "akk_tma");
  CheckContiguous(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckDtype(arg_tma_descriptor_workspace, "tma_descriptor_workspace", 1, 8, 1);
  CAKE_HOST_CHECK(arg_tma_descriptor_workspace.numel() >= 384, ValueError)
      << "tma_descriptor_workspace requires at least 384 bytes";
  CAKE_HOST_CHECK(
      reinterpret_cast<uintptr_t>(arg_tma_descriptor_workspace.data_ptr()) % 128 == 0,
      ValueError)
      << "tma_descriptor_workspace must be 128-byte aligned";
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  CUtensorMap h_akk_tma = EncodeTma_akk_tma(arg_akk_tma);
  CakeTensorMap const* p_akk_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 0u));
  CUtensorMap h_vb_tma = EncodeTma_vb_tma(arg_vb_tma);
  CakeTensorMap const* p_vb_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 1u));
  CUtensorMap h_kb_tma = EncodeTma_kb_tma(arg_kb_tma);
  CakeTensorMap const* p_kb_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 2u));
  __nv_bfloat16* p_u_out = static_cast<__nv_bfloat16*>(arg_u_out.data_ptr());
  __nv_bfloat16* p_w_out = static_cast<__nv_bfloat16*>(arg_w_out.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  void* kargs[] = {&p_akk_tma, &p_vb_tma, &p_kb_tma, &p_u_out, &p_w_out, &v_num_heads};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_kda_chunk_train_61eaa8af22292a7ef117),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            99328);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  CAKE_HOST_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_kda_chunk_train_61eaa8af22292a7ef117 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(192u, 1u, 1u);
  const CUtensorMap workspace_maps[] = {h_akk_tma, h_vb_tma, h_kb_tma};
  UploadCallerTmaWorkspace(arg_tma_descriptor_workspace.data_ptr(), workspace_maps, stream);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 99328u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_kda_chunk_train_61eaa8af22292a7ef117), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_kda_chunk_train_61eaa8af22292a7ef117 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_0de6f99a5ec28a53

CAKE_HOST_STAGE(wy, cake_host_shim_0de6f99a5ec28a53::Run);
