apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-gpu-test
  namespace: nlp
spec:
  selector:
    matchLabels:
      app: demo-gpu
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-gpu
    spec:
      containers:
      - name: demo-gpu-test
        image: harbor.unisound.ai/unisound/trajectory_gene:gpu-test 
        securityContext:
         privileged: true 
        command:
        - /bin/bash
        - -c
        - /etc/init.d/docker start && sleep 360d
        env:
        - name: http_proxy
          value: ""
        - name: https_proxy
          value: ""
        - name: HTTP_PROXY
          value: ""
        - name: HTTPS_PROXY
          value: ""
        - name: no_proxy
          value: localhost,127.0.0.1,::1
        - name: NO_PROXY
          value: localhost,127.0.0.1,::1
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP      
        resources:
          limits:
            cpu: 64
            memory: 512Gi
            nvidia.com/gpu: 8
        volumeMounts:
        - name: jfs
          mountPath: /fs
        - name: dshm
          mountPath: /dev/shm 
        - name: docker-storage
          mountPath: /var/lib/docker
      volumes:
      - name: jfs
        hostPath:
          path: /fs #必须填写，对应调试机的目录
      - name: dshm
        emptyDir: { medium: Memory, sizeLimit: 64Gi }
      - name: docker-storage
        emptyDir: {}
