"""Deterministic chunked gated delta rule (GDN) training kernels for Blackwell (SM100a / SM103a).

Generated by the Cake compiler from the flash-linear-attention v0.5.2 ``chunk_gated_delta_rule``
dataflow (chunk 64, K = V = 128, in-kernel q/k L2 normalisation): forward and backward as
register-MMA kernels with fp32 inter-chunk state carriers, bf16 hand-offs at the reference's
rounding points and fixed-order reductions without atomics, so repeated passes on identical inputs
are bit-identical.  :func:`chunk_gated_delta_rule` has FLA's signature and autograd contract,
including ``cu_seqlens`` packing and ``cp_context`` state passing.
"""

from ..cake_native import SUPPORTED_CAPABILITIES, device_arch
from .ops import chunk_gated_delta_rule

__all__ = ["SUPPORTED_CAPABILITIES", "chunk_gated_delta_rule", "device_arch"]
