release:
    #!/bin/bash
    set -euxo pipefail

    cd ..

    docker build -f docker/Dockerfile . -t radixark/miles:$VERSION
    docker push radixark/miles:$VERSION

    docker tag radixark/miles:$VERSION radixark/miles:latest
    docker push radixark/miles:latest
