/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_kda_chunk_train_f36b958b2e98912bca25' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

struct CakeTensorMap;
extern "C" __global__ void kernel_cake_kda_chunk_train_f36b958b2e98912bca25(CakeTensorMap const* kg_tma, CakeTensorMap const* qg_tma, CakeTensorMap const* w_tma, CakeTensorMap const* do_tma, __nv_bfloat16* __restrict__ dv1, float* __restrict__ gk, __nv_bfloat16* __restrict__ dh_out, __nv_bfloat16* __restrict__ dv2, int num_heads, int* __restrict__ seq_chunk_start, float scale);


namespace cake_host_shim_cac80528a555243e {

using cake_host::Optional;
using cake_host::TensorView;

class ScopedCudaDevice {
 public:
  explicit ScopedCudaDevice(int device_id) {
    cudaError_t error = cudaGetDevice(&previous_device_);
    CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
        << "cudaGetDevice failed before host-shim launch: cudaError="
        << static_cast<int>(error);
    if (previous_device_ != device_id) {
      error = cudaSetDevice(device_id);
      CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
          << "cudaSetDevice failed before host-shim launch for cuda:"
          << device_id << ": cudaError=" << static_cast<int>(error);
      restore_ = true;
    }
  }

  ScopedCudaDevice(const ScopedCudaDevice&) = delete;
  ScopedCudaDevice& operator=(const ScopedCudaDevice&) = delete;

  ~ScopedCudaDevice() noexcept {
    if (restore_) {
      (void)cudaSetDevice(previous_device_);
    }
  }

 private:
  int previous_device_ = -1;
  bool restore_ = false;
};

inline int64_t CakeDeviceMultiprocessorCount(int device_id) {
  constexpr int kMaxCachedCudaDevices = 64;
  CAKE_HOST_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "physical-SM-count cache does not cover cuda:" << device_id;
  static std::atomic<int> count_by_device[kMaxCachedCudaDevices]{};
  int cached = count_by_device[device_id].load(std::memory_order_acquire);
  if (cached > 0) return cached;

  int count = 0;
  cudaError_t error = cudaDeviceGetAttribute(
      &count, cudaDevAttrMultiProcessorCount, device_id);
  CAKE_HOST_CHECK(error == cudaSuccess && count > 0, RuntimeError)
      << "querying multiProcessorCount failed for cuda:" << device_id
      << ": cudaError=" << static_cast<int>(error) << ", count=" << count;
  // Concurrent first launches may repeat the immutable device query, but all
  // publication is atomic and every later hot-path lookup is one acquire load.
  count_by_device[device_id].store(count, std::memory_order_release);
  return count;
}

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  CAKE_HOST_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(
    const TensorView& t,
    const TensorView& reference,
    const char* name,
    const char* reference_name) {
  CAKE_HOST_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id
      << " versus cuda:" << reference.device().device_id;
}

inline void CheckCurrentCudaDevice(
    const TensorView& reference,
    const char* reference_name) {
  int current_device = -1;
  cudaError_t error = cudaGetDevice(&current_device);
  CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
      << "cudaGetDevice failed while validating " << reference_name
      << ": cudaError=" << static_cast<int>(error);
  CAKE_HOST_CHECK(current_device == reference.device().device_id, ValueError)
      << "current CUDA device must match " << reference_name
      << ": current=cuda:" << current_device
      << ", tensor=cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  CAKE_HOST_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  CAKE_HOST_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  CAKE_HOST_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  CAKE_HOST_CHECK(step > 0, ValueError)
      << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      CAKE_HOST_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis)
          << ", expected " << expected;
    }
  }
}

// Caller-owned storage is mutable scratch, including when its address and
// underlying CUDA allocation stay unchanged. Refresh all descriptors on the
// launch stream every time; allocation identity cannot establish their contents.
// By-value kernel parameters make the upload independent of host-buffer lifetime
// and record the descriptor bytes in CUDA Graphs for every replay.
template <size_t N>
struct CallerTmaDescriptorBatch {
  uint4 words[N * sizeof(CUtensorMap) / sizeof(uint4)];
};

template <size_t N>
__global__ void UploadCallerTmaDescriptors(
    uint4* workspace, CallerTmaDescriptorBatch<N> descriptors) {
  for (size_t i = threadIdx.x;
       i < N * sizeof(CUtensorMap) / sizeof(uint4); i += blockDim.x) {
    workspace[i] = descriptors.words[i];
  }
  // Generated pointer-ABI consumers acquire the tensor-map proxy before use.
  asm volatile("fence.proxy.tensormap::generic.release.sys;" ::: "memory");
}

template <size_t N>
static inline void UploadCallerTmaWorkspace(
    void* workspace, const CUtensorMap (&maps)[N], cudaStream_t stream) {
  CallerTmaDescriptorBatch<N> descriptors;
  static_assert(sizeof(descriptors) == sizeof(maps), "tensor-map batch ABI");
  std::memcpy(&descriptors, maps, sizeof(maps));
  void* args[] = {&workspace, &descriptors};
  cudaError_t result = cudaLaunchKernel(
      reinterpret_cast<const void*>(UploadCallerTmaDescriptors<N>),
      dim3(1), dim3(32), args, 0, stream);
  CAKE_HOST_CHECK(result == cudaSuccess, RuntimeError)
      << "uploading caller-owned TMA descriptors failed: "
      << cudaGetErrorString(result);
}

static inline void* CallerTmaWorkspaceSlot(
    const cake_host::TensorView& workspace,
    size_t slot) {
  const uintptr_t base = reinterpret_cast<uintptr_t>(workspace.data_ptr());
  const uintptr_t address = base + slot * sizeof(CUtensorMap);
  return reinterpret_cast<void*>(address);
}

// 3D TMA descriptor for buffer 'kg_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_kg_tma(const TensorView& t) {
  CAKE_HOST_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'kg_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  CAKE_HOST_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'kg_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  CAKE_HOST_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'kg_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  CAKE_HOST_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'kg_tma' resolved a non-positive global dim";
  CAKE_HOST_CHECK(64u <= global_dim[0] && 1u <= global_dim[1] && 64u <= global_dim[2], ValueError)
      << "TMA box (64, 1, 64) exceeds resolved global dims for 'kg_tma'";
  int64_t carrier_stride_0 = d1;
  CAKE_HOST_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'kg_tma' resolved global stride 1 negative";
  CAKE_HOST_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'kg_tma' resolved global stride 1 zero while global dimension 1 is not 1";
  CAKE_HOST_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'kg_tma' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = (d1 * d2);
  CAKE_HOST_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'kg_tma' resolved global stride 2 negative";
  CAKE_HOST_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'kg_tma' resolved global stride 2 zero while global dimension 2 is not 1";
  CAKE_HOST_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'kg_tma' resolved global stride 2 to a non-whole-byte offset";
  uint64_t global_strides[2] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
  };
  uint32_t box_dim[3] = {64u, 1u, 64u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  CAKE_HOST_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'kg_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 3D TMA descriptor for buffer 'qg_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_qg_tma(const TensorView& t) {
  CAKE_HOST_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'qg_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  CAKE_HOST_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'qg_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  CAKE_HOST_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'qg_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  CAKE_HOST_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'qg_tma' resolved a non-positive global dim";
  CAKE_HOST_CHECK(64u <= global_dim[0] && 1u <= global_dim[1] && 64u <= global_dim[2], ValueError)
      << "TMA box (64, 1, 64) exceeds resolved global dims for 'qg_tma'";
  int64_t carrier_stride_0 = d1;
  CAKE_HOST_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'qg_tma' resolved global stride 1 negative";
  CAKE_HOST_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'qg_tma' resolved global stride 1 zero while global dimension 1 is not 1";
  CAKE_HOST_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'qg_tma' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = (d1 * d2);
  CAKE_HOST_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'qg_tma' resolved global stride 2 negative";
  CAKE_HOST_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'qg_tma' resolved global stride 2 zero while global dimension 2 is not 1";
  CAKE_HOST_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'qg_tma' resolved global stride 2 to a non-whole-byte offset";
  uint64_t global_strides[2] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
  };
  uint32_t box_dim[3] = {64u, 1u, 64u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  CAKE_HOST_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'qg_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 3D TMA descriptor for buffer 'w_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_w_tma(const TensorView& t) {
  CAKE_HOST_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'w_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  CAKE_HOST_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'w_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  CAKE_HOST_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'w_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  CAKE_HOST_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'w_tma' resolved a non-positive global dim";
  CAKE_HOST_CHECK(64u <= global_dim[0] && 1u <= global_dim[1] && 64u <= global_dim[2], ValueError)
      << "TMA box (64, 1, 64) exceeds resolved global dims for 'w_tma'";
  int64_t carrier_stride_0 = d1;
  CAKE_HOST_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'w_tma' resolved global stride 1 negative";
  CAKE_HOST_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'w_tma' resolved global stride 1 zero while global dimension 1 is not 1";
  CAKE_HOST_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'w_tma' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = (d1 * d2);
  CAKE_HOST_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'w_tma' resolved global stride 2 negative";
  CAKE_HOST_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'w_tma' resolved global stride 2 zero while global dimension 2 is not 1";
  CAKE_HOST_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'w_tma' resolved global stride 2 to a non-whole-byte offset";
  uint64_t global_strides[2] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
  };
  uint32_t box_dim[3] = {64u, 1u, 64u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_128B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  CAKE_HOST_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'w_tma') failed: CUresult=" << (int)r;
  return tm;
}

// 3D TMA descriptor for buffer 'do_tma' — compiled from the
// descriptor's std.Expr global_dim/global_strides/checks record.
inline CUtensorMap EncodeTma_do_tma(const TensorView& t) {
  CAKE_HOST_CHECK(t.ndim() >= 2, ValueError)
      << "TMA source 'do_tma' must have at least 2 dimensions, got ndim=" << t.ndim();
  CAKE_HOST_CHECK(t.stride(-1) == 1, ValueError)
      << "TMA source 'do_tma' must have unit innermost stride, got " << t.stride(-1);
  int64_t d1 = t.size(t.ndim() - 1);
  int64_t d2 = t.size(t.ndim() - 2);
  CAKE_HOST_CHECK(d1 > 0 && d2 > 0, ValueError)
      << "TMA source 'do_tma' trailing dims must be positive";
  int64_t outer2 = t.numel() / (d1 * d2);
  uint64_t global_dim[3] = {(uint64_t)(d1), (uint64_t)(d2), (uint64_t)(outer2)};
  CAKE_HOST_CHECK(global_dim[0] > 0 && global_dim[1] > 0 && global_dim[2] > 0, ValueError)
      << "TMA descriptor for 'do_tma' resolved a non-positive global dim";
  CAKE_HOST_CHECK(32u <= global_dim[0] && 1u <= global_dim[1] && 64u <= global_dim[2], ValueError)
      << "TMA box (32, 1, 64) exceeds resolved global dims for 'do_tma'";
  int64_t carrier_stride_0 = d1;
  CAKE_HOST_CHECK(carrier_stride_0 >= 0, ValueError)
      << "TMA descriptor for 'do_tma' resolved global stride 1 negative";
  CAKE_HOST_CHECK(carrier_stride_0 != 0 || global_dim[1] == 1, ValueError)
      << "TMA descriptor for 'do_tma' resolved global stride 1 zero while global dimension 1 is not 1";
  CAKE_HOST_CHECK((carrier_stride_0 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'do_tma' resolved global stride 1 to a non-whole-byte offset";
  int64_t carrier_stride_1 = (d1 * d2);
  CAKE_HOST_CHECK(carrier_stride_1 >= 0, ValueError)
      << "TMA descriptor for 'do_tma' resolved global stride 2 negative";
  CAKE_HOST_CHECK(carrier_stride_1 != 0 || global_dim[2] == 1, ValueError)
      << "TMA descriptor for 'do_tma' resolved global stride 2 zero while global dimension 2 is not 1";
  CAKE_HOST_CHECK((carrier_stride_1 * 16) % 8 == 0, ValueError)
      << "TMA descriptor for 'do_tma' resolved global stride 2 to a non-whole-byte offset";
  uint64_t global_strides[2] = {
      (uint64_t)((carrier_stride_0 * 16) / 8),
      (uint64_t)((carrier_stride_1 * 16) / 8),
  };
  uint32_t box_dim[3] = {32u, 1u, 64u};
  uint32_t elem_strides[3] = {1u, 1u, 1u};
  CUtensorMap tm{};
  const void* tensor_base = static_cast<const char*>(t.data_ptr()) + 0u;
  CUresult r = cuTensorMapEncodeTiled(
      &tm, CU_TENSOR_MAP_DATA_TYPE_BFLOAT16, 3, const_cast<void*>(tensor_base), global_dim, global_strides, box_dim, elem_strides,
      CU_TENSOR_MAP_INTERLEAVE_NONE, CU_TENSOR_MAP_SWIZZLE_64B, CU_TENSOR_MAP_L2_PROMOTION_NONE,
      CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE);
  CAKE_HOST_CHECK(r == CUDA_SUCCESS, RuntimeError)
      << "cuTensorMapEncodeTiled (3D, 'do_tma') failed: CUresult=" << (int)r;
  return tm;
}

void Run(TensorView arg_kg_tma, TensorView arg_qg_tma, TensorView arg_w_tma, TensorView arg_do_tma, TensorView arg_dv1, TensorView arg_gk, TensorView arg_dh_out, TensorView arg_dv2, int64_t arg_num_heads, TensorView arg_seq_chunk_start, double arg_scale, TensorView arg_tma_descriptor_workspace, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_kg_tma.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_kg_tma, "kg_tma");
  CheckDtype(arg_kg_tma, "kg_tma", 4, 16, 1);
  CheckContiguous(arg_kg_tma, "kg_tma");
  CheckCudaTensor(arg_qg_tma, "qg_tma");
  CheckDtype(arg_qg_tma, "qg_tma", 4, 16, 1);
  CheckContiguous(arg_qg_tma, "qg_tma");
  CheckCudaTensor(arg_w_tma, "w_tma");
  CheckDtype(arg_w_tma, "w_tma", 4, 16, 1);
  CheckContiguous(arg_w_tma, "w_tma");
  CheckCudaTensor(arg_do_tma, "do_tma");
  CheckDtype(arg_do_tma, "do_tma", 4, 16, 1);
  CheckContiguous(arg_do_tma, "do_tma");
  CheckCudaTensor(arg_dv1, "dv1");
  CheckDtype(arg_dv1, "dv1", 4, 16, 1);
  CheckContiguous(arg_dv1, "dv1");
  CheckCudaTensor(arg_gk, "gk");
  CheckDtype(arg_gk, "gk", 2, 32, 1);
  CheckContiguous(arg_gk, "gk");
  CheckCudaTensor(arg_dh_out, "dh_out");
  CheckDtype(arg_dh_out, "dh_out", 4, 16, 1);
  CheckContiguous(arg_dh_out, "dh_out");
  CheckCudaTensor(arg_dv2, "dv2");
  CheckDtype(arg_dv2, "dv2", 4, 16, 1);
  CheckContiguous(arg_dv2, "dv2");
  CAKE_HOST_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckCudaTensor(arg_seq_chunk_start, "seq_chunk_start");
  CheckDtype(arg_seq_chunk_start, "seq_chunk_start", 0, 32, 1);
  CheckContiguous(arg_seq_chunk_start, "seq_chunk_start");
  CheckSameCudaDevice(arg_qg_tma, arg_kg_tma, "qg_tma", "kg_tma");
  CheckSameCudaDevice(arg_w_tma, arg_kg_tma, "w_tma", "kg_tma");
  CheckSameCudaDevice(arg_do_tma, arg_kg_tma, "do_tma", "kg_tma");
  CheckSameCudaDevice(arg_dv1, arg_kg_tma, "dv1", "kg_tma");
  CheckSameCudaDevice(arg_gk, arg_kg_tma, "gk", "kg_tma");
  CheckSameCudaDevice(arg_dh_out, arg_kg_tma, "dh_out", "kg_tma");
  CheckSameCudaDevice(arg_dv2, arg_kg_tma, "dv2", "kg_tma");
  CheckSameCudaDevice(arg_seq_chunk_start, arg_kg_tma, "seq_chunk_start", "kg_tma");
  CheckCurrentCudaDevice(arg_kg_tma, "kg_tma");
  CheckCudaTensor(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckSameCudaDevice(arg_tma_descriptor_workspace, arg_kg_tma, "tma_descriptor_workspace", "kg_tma");
  CheckContiguous(arg_tma_descriptor_workspace, "tma_descriptor_workspace");
  CheckDtype(arg_tma_descriptor_workspace, "tma_descriptor_workspace", 1, 8, 1);
  CAKE_HOST_CHECK(arg_tma_descriptor_workspace.numel() >= 512, ValueError)
      << "tma_descriptor_workspace requires at least 512 bytes";
  CAKE_HOST_CHECK(
      reinterpret_cast<uintptr_t>(arg_tma_descriptor_workspace.data_ptr()) % 128 == 0,
      ValueError)
      << "tma_descriptor_workspace must be 128-byte aligned";
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  CUtensorMap h_kg_tma = EncodeTma_kg_tma(arg_kg_tma);
  CakeTensorMap const* p_kg_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 0u));
  CUtensorMap h_qg_tma = EncodeTma_qg_tma(arg_qg_tma);
  CakeTensorMap const* p_qg_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 1u));
  CUtensorMap h_w_tma = EncodeTma_w_tma(arg_w_tma);
  CakeTensorMap const* p_w_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 2u));
  CUtensorMap h_do_tma = EncodeTma_do_tma(arg_do_tma);
  CakeTensorMap const* p_do_tma = static_cast<CakeTensorMap const*>(CallerTmaWorkspaceSlot(arg_tma_descriptor_workspace, 3u));
  __nv_bfloat16* p_dv1 = static_cast<__nv_bfloat16*>(arg_dv1.data_ptr());
  float* p_gk = static_cast<float*>(arg_gk.data_ptr());
  __nv_bfloat16* p_dh_out = static_cast<__nv_bfloat16*>(arg_dh_out.data_ptr());
  __nv_bfloat16* p_dv2 = static_cast<__nv_bfloat16*>(arg_dv2.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int* p_seq_chunk_start = static_cast<int*>(arg_seq_chunk_start.data_ptr());
  float v_scale = (float)arg_scale;
  void* kargs[] = {&p_kg_tma, &p_qg_tma, &p_w_tma, &p_do_tma, &p_dv1, &p_gk, &p_dh_out, &p_dv2, &v_num_heads, &p_seq_chunk_start, &v_scale};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_kda_chunk_train_f36b958b2e98912bca25),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            119808);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  CAKE_HOST_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_kda_chunk_train_f36b958b2e98912bca25 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(192u, 1u, 1u);
  const CUtensorMap workspace_maps[] = {h_kg_tma, h_qg_tma, h_w_tma, h_do_tma};
  UploadCallerTmaWorkspace(arg_tma_descriptor_workspace.data_ptr(), workspace_maps, stream);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 119808u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_kda_chunk_train_f36b958b2e98912bca25), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_kda_chunk_train_f36b958b2e98912bca25 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_cac80528a555243e

CAKE_HOST_EXPORT(run, cake_host_shim_cac80528a555243e::Run);
