from __future__ import annotations

SUBPROCESS_INDEX_ENV_VAR = "MILES_SUPERVISOR_SUBPROCESS_INDEX"
CELL_INDEX_ENV_VAR = "MILES_CELL_INDEX"
POD_INDEX_ENV_VAR = "MILES_POD_INDEX"

PLATFORM_IDENTITY_ENV_VARS = (SUBPROCESS_INDEX_ENV_VAR, CELL_INDEX_ENV_VAR, POD_INDEX_ENV_VAR)
