/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_dsa_train_9947659b8a972e6c655a' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_dsa_train_9947659b8a972e6c655a(__nv_bfloat16* __restrict__ index_q, __nv_bfloat16* __restrict__ index_k, float* __restrict__ weights, int* __restrict__ topk_indices, float* __restrict__ grad_scores, __nv_bfloat16* __restrict__ d_index_q, float* __restrict__ d_weights, float* __restrict__ partial, int heads, int topk);


namespace cake_host_shim_4e4eb8e081b70a05 {

using cake_host::Optional;
using cake_host::TensorView;

class ScopedCudaDevice {
 public:
  explicit ScopedCudaDevice(int device_id) {
    cudaError_t error = cudaGetDevice(&previous_device_);
    CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
        << "cudaGetDevice failed before host-shim launch: cudaError="
        << static_cast<int>(error);
    if (previous_device_ != device_id) {
      error = cudaSetDevice(device_id);
      CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
          << "cudaSetDevice failed before host-shim launch for cuda:"
          << device_id << ": cudaError=" << static_cast<int>(error);
      restore_ = true;
    }
  }

  ScopedCudaDevice(const ScopedCudaDevice&) = delete;
  ScopedCudaDevice& operator=(const ScopedCudaDevice&) = delete;

  ~ScopedCudaDevice() noexcept {
    if (restore_) {
      (void)cudaSetDevice(previous_device_);
    }
  }

 private:
  int previous_device_ = -1;
  bool restore_ = false;
};

inline int64_t CakeDeviceMultiprocessorCount(int device_id) {
  constexpr int kMaxCachedCudaDevices = 64;
  CAKE_HOST_CHECK(device_id >= 0 && device_id < kMaxCachedCudaDevices, RuntimeError)
      << "physical-SM-count cache does not cover cuda:" << device_id;
  static std::atomic<int> count_by_device[kMaxCachedCudaDevices]{};
  int cached = count_by_device[device_id].load(std::memory_order_acquire);
  if (cached > 0) return cached;

  int count = 0;
  cudaError_t error = cudaDeviceGetAttribute(
      &count, cudaDevAttrMultiProcessorCount, device_id);
  CAKE_HOST_CHECK(error == cudaSuccess && count > 0, RuntimeError)
      << "querying multiProcessorCount failed for cuda:" << device_id
      << ": cudaError=" << static_cast<int>(error) << ", count=" << count;
  // Concurrent first launches may repeat the immutable device query, but all
  // publication is atomic and every later hot-path lookup is one acquire load.
  count_by_device[device_id].store(count, std::memory_order_release);
  return count;
}

inline void CheckCudaTensor(const TensorView& t, const char* name) {
  CAKE_HOST_CHECK(t.device().device_type == kDLCUDA, ValueError)
      << name << " must be a CUDA tensor, got device_type=" << (int)t.device().device_type;
}

inline void CheckSameCudaDevice(
    const TensorView& t,
    const TensorView& reference,
    const char* name,
    const char* reference_name) {
  CAKE_HOST_CHECK(t.device().device_id == reference.device().device_id, ValueError)
      << name << " must be on the same CUDA device as " << reference_name
      << ": got cuda:" << t.device().device_id
      << " versus cuda:" << reference.device().device_id;
}

inline void CheckCurrentCudaDevice(
    const TensorView& reference,
    const char* reference_name) {
  int current_device = -1;
  cudaError_t error = cudaGetDevice(&current_device);
  CAKE_HOST_CHECK(error == cudaSuccess, RuntimeError)
      << "cudaGetDevice failed while validating " << reference_name
      << ": cudaError=" << static_cast<int>(error);
  CAKE_HOST_CHECK(current_device == reference.device().device_id, ValueError)
      << "current CUDA device must match " << reference_name
      << ": current=cuda:" << current_device
      << ", tensor=cuda:" << reference.device().device_id;
}

inline void CheckContiguous(const TensorView& t, const char* name) {
  CAKE_HOST_CHECK(t.IsContiguous(), ValueError) << name << " must be contiguous";
}

inline void CheckDtype(const TensorView& t, const char* name, int code, int bits, int lanes) {
  DLDataType d = t.dtype();
  CAKE_HOST_CHECK((int)d.code == code && (int)d.bits == bits && (int)d.lanes == lanes, TypeError)
      << name << " dtype mismatch: expected DLDataType(code=" << code << ", bits=" << bits
      << ", lanes=" << lanes << "), got (code=" << (int)d.code << ", bits=" << (int)d.bits
      << ", lanes=" << (int)d.lanes << ")";
}

// A logical axis.outer(trailing) folds every source dim above the trailing
// dimensions. Shape products are independent of physical strides, so verify
// the leading dimensions form one dense row-major chain instead of inventing
// a "folded stride". The descriptor reads its exact adjacent physical step
// separately through stride[-(trailing + 1)].
inline void CheckDenseLeadingFold(const TensorView& t, int trailing, const char* name) {
  CAKE_HOST_CHECK(trailing > 0 && t.ndim() >= trailing, ValueError)
      << name << " cannot fold leading dimensions above " << trailing
      << " trailing dims from ndim=" << t.ndim();
  int outer_last = t.ndim() - trailing - 1;
  if (outer_last <= 0) {
    return;
  }
  int64_t step = t.stride(outer_last);
  CAKE_HOST_CHECK(step > 0, ValueError)
      << name << " physical strides must be positive";
  int64_t expected = step;
  for (int axis = outer_last - 1; axis >= 0; --axis) {
    expected *= t.size(axis + 1);
    if (t.size(axis) > 1) {
      CAKE_HOST_CHECK(t.stride(axis) == expected, ValueError)
          << name << " leading dims are not physically foldable above " << trailing
          << " trailing dims: stride(" << axis << ")=" << t.stride(axis)
          << ", expected " << expected;
    }
  }
}

void Run(TensorView arg_index_q, TensorView arg_index_k, TensorView arg_weights, TensorView arg_topk_indices, TensorView arg_grad_scores, TensorView arg_d_index_q, TensorView arg_d_weights, TensorView arg_partial, int64_t arg_heads, int64_t arg_topk, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_index_q.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_index_q, "index_q");
  CheckDtype(arg_index_q, "index_q", 4, 16, 1);
  CheckContiguous(arg_index_q, "index_q");
  CheckCudaTensor(arg_index_k, "index_k");
  CheckDtype(arg_index_k, "index_k", 4, 16, 1);
  CheckContiguous(arg_index_k, "index_k");
  CheckCudaTensor(arg_weights, "weights");
  CheckDtype(arg_weights, "weights", 2, 32, 1);
  CheckContiguous(arg_weights, "weights");
  CheckCudaTensor(arg_topk_indices, "topk_indices");
  CheckDtype(arg_topk_indices, "topk_indices", 0, 32, 1);
  CheckContiguous(arg_topk_indices, "topk_indices");
  CheckCudaTensor(arg_grad_scores, "grad_scores");
  CheckDtype(arg_grad_scores, "grad_scores", 2, 32, 1);
  CheckContiguous(arg_grad_scores, "grad_scores");
  CheckCudaTensor(arg_d_index_q, "d_index_q");
  CheckDtype(arg_d_index_q, "d_index_q", 4, 16, 1);
  CheckContiguous(arg_d_index_q, "d_index_q");
  CheckCudaTensor(arg_d_weights, "d_weights");
  CheckDtype(arg_d_weights, "d_weights", 2, 32, 1);
  CheckContiguous(arg_d_weights, "d_weights");
  CheckCudaTensor(arg_partial, "partial");
  CheckDtype(arg_partial, "partial", 2, 32, 1);
  CheckContiguous(arg_partial, "partial");
  CAKE_HOST_CHECK(arg_heads >= -2147483648LL && arg_heads <= 2147483647LL, ValueError)
      << "scalar 'heads' value " << arg_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_topk >= -2147483648LL && arg_topk <= 2147483647LL, ValueError)
      << "scalar 'topk' value " << arg_topk
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_index_k, arg_index_q, "index_k", "index_q");
  CheckSameCudaDevice(arg_weights, arg_index_q, "weights", "index_q");
  CheckSameCudaDevice(arg_topk_indices, arg_index_q, "topk_indices", "index_q");
  CheckSameCudaDevice(arg_grad_scores, arg_index_q, "grad_scores", "index_q");
  CheckSameCudaDevice(arg_d_index_q, arg_index_q, "d_index_q", "index_q");
  CheckSameCudaDevice(arg_d_weights, arg_index_q, "d_weights", "index_q");
  CheckSameCudaDevice(arg_partial, arg_index_q, "partial", "index_q");
  CheckCurrentCudaDevice(arg_index_q, "index_q");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_index_q = static_cast<__nv_bfloat16*>(arg_index_q.data_ptr());
  __nv_bfloat16* p_index_k = static_cast<__nv_bfloat16*>(arg_index_k.data_ptr());
  float* p_weights = static_cast<float*>(arg_weights.data_ptr());
  int* p_topk_indices = static_cast<int*>(arg_topk_indices.data_ptr());
  float* p_grad_scores = static_cast<float*>(arg_grad_scores.data_ptr());
  __nv_bfloat16* p_d_index_q = static_cast<__nv_bfloat16*>(arg_d_index_q.data_ptr());
  float* p_d_weights = static_cast<float*>(arg_d_weights.data_ptr());
  float* p_partial = static_cast<float*>(arg_partial.data_ptr());
  int32_t v_heads = (int32_t)arg_heads;
  int32_t v_topk = (int32_t)arg_topk;
  void* kargs[] = {&p_index_q, &p_index_k, &p_weights, &p_topk_indices, &p_grad_scores, &p_d_index_q, &p_d_weights, &p_partial, &v_heads, &v_topk};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 42240u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_dsa_train_9947659b8a972e6c655a), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_dsa_train_9947659b8a972e6c655a failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_4e4eb8e081b70a05

CAKE_HOST_EXPORT(run, cake_host_shim_4e4eb8e081b70a05::Run);
