/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_gdn_chunk_train_b74437f320f86bd86e02' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_gdn_chunk_train_b74437f320f86bd86e02(int* __restrict__ cu_seqlens, int* __restrict__ chunk_start, int* __restrict__ chunk_len, int* __restrict__ seq_chunk_start, int num_seqs, int num_chunks_max, int total_tokens);


namespace cake_host_shim_b924e67dd51a58bb {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_cu_seqlens, TensorView arg_chunk_start, TensorView arg_chunk_len, TensorView arg_seq_chunk_start, int64_t arg_num_seqs, int64_t arg_num_chunks_max, int64_t arg_total_tokens, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_cu_seqlens.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_cu_seqlens, "cu_seqlens");
  CheckDtype(arg_cu_seqlens, "cu_seqlens", 0, 32, 1);
  CheckContiguous(arg_cu_seqlens, "cu_seqlens");
  CheckCudaTensor(arg_chunk_start, "chunk_start");
  CheckDtype(arg_chunk_start, "chunk_start", 0, 32, 1);
  CheckContiguous(arg_chunk_start, "chunk_start");
  CheckCudaTensor(arg_chunk_len, "chunk_len");
  CheckDtype(arg_chunk_len, "chunk_len", 0, 32, 1);
  CheckContiguous(arg_chunk_len, "chunk_len");
  CheckCudaTensor(arg_seq_chunk_start, "seq_chunk_start");
  CheckDtype(arg_seq_chunk_start, "seq_chunk_start", 0, 32, 1);
  CheckContiguous(arg_seq_chunk_start, "seq_chunk_start");
  CAKE_HOST_CHECK(arg_num_seqs >= -2147483648LL && arg_num_seqs <= 2147483647LL, ValueError)
      << "scalar 'num_seqs' value " << arg_num_seqs
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_chunks_max >= -2147483648LL && arg_num_chunks_max <= 2147483647LL, ValueError)
      << "scalar 'num_chunks_max' value " << arg_num_chunks_max
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_total_tokens >= -2147483648LL && arg_total_tokens <= 2147483647LL, ValueError)
      << "scalar 'total_tokens' value " << arg_total_tokens
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_chunk_start, arg_cu_seqlens, "chunk_start", "cu_seqlens");
  CheckSameCudaDevice(arg_chunk_len, arg_cu_seqlens, "chunk_len", "cu_seqlens");
  CheckSameCudaDevice(arg_seq_chunk_start, arg_cu_seqlens, "seq_chunk_start", "cu_seqlens");
  CheckCurrentCudaDevice(arg_cu_seqlens, "cu_seqlens");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  int* p_cu_seqlens = static_cast<int*>(arg_cu_seqlens.data_ptr());
  int* p_chunk_start = static_cast<int*>(arg_chunk_start.data_ptr());
  int* p_chunk_len = static_cast<int*>(arg_chunk_len.data_ptr());
  int* p_seq_chunk_start = static_cast<int*>(arg_seq_chunk_start.data_ptr());
  int32_t v_num_seqs = (int32_t)arg_num_seqs;
  int32_t v_num_chunks_max = (int32_t)arg_num_chunks_max;
  int32_t v_total_tokens = (int32_t)arg_total_tokens;
  void* kargs[] = {&p_cu_seqlens, &p_chunk_start, &p_chunk_len, &p_seq_chunk_start, &v_num_seqs, &v_num_chunks_max, &v_total_tokens};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 0u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_b74437f320f86bd86e02), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_gdn_chunk_train_b74437f320f86bd86e02 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_b924e67dd51a58bb

CAKE_HOST_STAGE(meta, cake_host_shim_b924e67dd51a58bb::Run);
