/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_gdn_chunk_train_4b68db2b14106df8779b' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_gdn_chunk_train_4b68db2b14106df8779b(__nv_bfloat16* __restrict__ kn, __nv_bfloat16* __restrict__ v, __nv_bfloat16* __restrict__ A, __nv_bfloat16* __restrict__ dw, __nv_bfloat16* __restrict__ du, float* __restrict__ g_cs, float* __restrict__ beta, __nv_bfloat16* __restrict__ dk2_out, __nv_bfloat16* __restrict__ dv_out, __nv_bfloat16* __restrict__ dbeta_out, float* __restrict__ dg2_out, int* __restrict__ chunk_start, int* __restrict__ chunk_len, int num_heads, int num_v_heads);


namespace cake_host_shim_a939e327d116d66f {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_kn, TensorView arg_v, TensorView arg_A, TensorView arg_dw, TensorView arg_du, TensorView arg_g_cs, TensorView arg_beta, TensorView arg_dk2_out, TensorView arg_dv_out, TensorView arg_dbeta_out, TensorView arg_dg2_out, TensorView arg_chunk_start, TensorView arg_chunk_len, int64_t arg_num_heads, int64_t arg_num_v_heads, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_kn.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_kn, "kn");
  CheckDtype(arg_kn, "kn", 4, 16, 1);
  CheckContiguous(arg_kn, "kn");
  CheckCudaTensor(arg_v, "v");
  CheckDtype(arg_v, "v", 4, 16, 1);
  CheckContiguous(arg_v, "v");
  CheckCudaTensor(arg_A, "A");
  CheckDtype(arg_A, "A", 4, 16, 1);
  CheckContiguous(arg_A, "A");
  CheckCudaTensor(arg_dw, "dw");
  CheckDtype(arg_dw, "dw", 4, 16, 1);
  CheckContiguous(arg_dw, "dw");
  CheckCudaTensor(arg_du, "du");
  CheckDtype(arg_du, "du", 4, 16, 1);
  CheckContiguous(arg_du, "du");
  CheckCudaTensor(arg_g_cs, "g_cs");
  CheckDtype(arg_g_cs, "g_cs", 2, 32, 1);
  CheckContiguous(arg_g_cs, "g_cs");
  CheckCudaTensor(arg_beta, "beta");
  CheckDtype(arg_beta, "beta", 2, 32, 1);
  CheckContiguous(arg_beta, "beta");
  CheckCudaTensor(arg_dk2_out, "dk2_out");
  CheckDtype(arg_dk2_out, "dk2_out", 4, 16, 1);
  CheckContiguous(arg_dk2_out, "dk2_out");
  CheckCudaTensor(arg_dv_out, "dv_out");
  CheckDtype(arg_dv_out, "dv_out", 4, 16, 1);
  CheckContiguous(arg_dv_out, "dv_out");
  CheckCudaTensor(arg_dbeta_out, "dbeta_out");
  CheckDtype(arg_dbeta_out, "dbeta_out", 4, 16, 1);
  CheckContiguous(arg_dbeta_out, "dbeta_out");
  CheckCudaTensor(arg_dg2_out, "dg2_out");
  CheckDtype(arg_dg2_out, "dg2_out", 2, 32, 1);
  CheckContiguous(arg_dg2_out, "dg2_out");
  CheckCudaTensor(arg_chunk_start, "chunk_start");
  CheckDtype(arg_chunk_start, "chunk_start", 0, 32, 1);
  CheckContiguous(arg_chunk_start, "chunk_start");
  CheckCudaTensor(arg_chunk_len, "chunk_len");
  CheckDtype(arg_chunk_len, "chunk_len", 0, 32, 1);
  CheckContiguous(arg_chunk_len, "chunk_len");
  CAKE_HOST_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_v_heads >= -2147483648LL && arg_num_v_heads <= 2147483647LL, ValueError)
      << "scalar 'num_v_heads' value " << arg_num_v_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_v, arg_kn, "v", "kn");
  CheckSameCudaDevice(arg_A, arg_kn, "A", "kn");
  CheckSameCudaDevice(arg_dw, arg_kn, "dw", "kn");
  CheckSameCudaDevice(arg_du, arg_kn, "du", "kn");
  CheckSameCudaDevice(arg_g_cs, arg_kn, "g_cs", "kn");
  CheckSameCudaDevice(arg_beta, arg_kn, "beta", "kn");
  CheckSameCudaDevice(arg_dk2_out, arg_kn, "dk2_out", "kn");
  CheckSameCudaDevice(arg_dv_out, arg_kn, "dv_out", "kn");
  CheckSameCudaDevice(arg_dbeta_out, arg_kn, "dbeta_out", "kn");
  CheckSameCudaDevice(arg_dg2_out, arg_kn, "dg2_out", "kn");
  CheckSameCudaDevice(arg_chunk_start, arg_kn, "chunk_start", "kn");
  CheckSameCudaDevice(arg_chunk_len, arg_kn, "chunk_len", "kn");
  CheckCurrentCudaDevice(arg_kn, "kn");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_kn = static_cast<__nv_bfloat16*>(arg_kn.data_ptr());
  __nv_bfloat16* p_v = static_cast<__nv_bfloat16*>(arg_v.data_ptr());
  __nv_bfloat16* p_A = static_cast<__nv_bfloat16*>(arg_A.data_ptr());
  __nv_bfloat16* p_dw = static_cast<__nv_bfloat16*>(arg_dw.data_ptr());
  __nv_bfloat16* p_du = static_cast<__nv_bfloat16*>(arg_du.data_ptr());
  float* p_g_cs = static_cast<float*>(arg_g_cs.data_ptr());
  float* p_beta = static_cast<float*>(arg_beta.data_ptr());
  __nv_bfloat16* p_dk2_out = static_cast<__nv_bfloat16*>(arg_dk2_out.data_ptr());
  __nv_bfloat16* p_dv_out = static_cast<__nv_bfloat16*>(arg_dv_out.data_ptr());
  __nv_bfloat16* p_dbeta_out = static_cast<__nv_bfloat16*>(arg_dbeta_out.data_ptr());
  float* p_dg2_out = static_cast<float*>(arg_dg2_out.data_ptr());
  int* p_chunk_start = static_cast<int*>(arg_chunk_start.data_ptr());
  int* p_chunk_len = static_cast<int*>(arg_chunk_len.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int32_t v_num_v_heads = (int32_t)arg_num_v_heads;
  void* kargs[] = {&p_kn, &p_v, &p_A, &p_dw, &p_du, &p_g_cs, &p_beta, &p_dk2_out, &p_dv_out, &p_dbeta_out, &p_dg2_out, &p_chunk_start, &p_chunk_len, &v_num_heads, &v_num_v_heads};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_4b68db2b14106df8779b),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            108032);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  CAKE_HOST_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_gdn_chunk_train_4b68db2b14106df8779b failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 108032u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_4b68db2b14106df8779b), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_gdn_chunk_train_4b68db2b14106df8779b failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_a939e327d116d66f

CAKE_HOST_STAGE(wy_bwd_bf16, cake_host_shim_a939e327d116d66f::Run);
