/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_gdn_chunk_train_7182c463b27a027fca5d' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_gdn_chunk_train_7182c463b27a027fca5d(__nv_bfloat16* __restrict__ qn, __nv_bfloat16* __restrict__ kn, float* __restrict__ rstd_q, float* __restrict__ rstd_k, __nv_bfloat16* __restrict__ dq_hv, __nv_bfloat16* __restrict__ dk_hv, __nv_bfloat16* __restrict__ dk2, float* __restrict__ dg1, float* __restrict__ dg2, __nv_bfloat16* __restrict__ dq_out, __nv_bfloat16* __restrict__ dk_out, float* __restrict__ dg_out, int* __restrict__ chunk_start, int* __restrict__ chunk_len, int num_heads, int num_v_heads, int normalize_qk);


namespace cake_host_shim_eb0c68226cf71481 {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_qn, TensorView arg_kn, TensorView arg_rstd_q, TensorView arg_rstd_k, TensorView arg_dq_hv, TensorView arg_dk_hv, TensorView arg_dk2, TensorView arg_dg1, TensorView arg_dg2, TensorView arg_dq_out, TensorView arg_dk_out, TensorView arg_dg_out, TensorView arg_chunk_start, TensorView arg_chunk_len, int64_t arg_num_heads, int64_t arg_num_v_heads, int64_t arg_normalize_qk, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_qn.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_qn, "qn");
  CheckDtype(arg_qn, "qn", 4, 16, 1);
  CheckContiguous(arg_qn, "qn");
  CheckCudaTensor(arg_kn, "kn");
  CheckDtype(arg_kn, "kn", 4, 16, 1);
  CheckContiguous(arg_kn, "kn");
  CheckCudaTensor(arg_rstd_q, "rstd_q");
  CheckDtype(arg_rstd_q, "rstd_q", 2, 32, 1);
  CheckContiguous(arg_rstd_q, "rstd_q");
  CheckCudaTensor(arg_rstd_k, "rstd_k");
  CheckDtype(arg_rstd_k, "rstd_k", 2, 32, 1);
  CheckContiguous(arg_rstd_k, "rstd_k");
  CheckCudaTensor(arg_dq_hv, "dq_hv");
  CheckDtype(arg_dq_hv, "dq_hv", 4, 16, 1);
  CheckContiguous(arg_dq_hv, "dq_hv");
  CheckCudaTensor(arg_dk_hv, "dk_hv");
  CheckDtype(arg_dk_hv, "dk_hv", 4, 16, 1);
  CheckContiguous(arg_dk_hv, "dk_hv");
  CheckCudaTensor(arg_dk2, "dk2");
  CheckDtype(arg_dk2, "dk2", 4, 16, 1);
  CheckContiguous(arg_dk2, "dk2");
  CheckCudaTensor(arg_dg1, "dg1");
  CheckDtype(arg_dg1, "dg1", 2, 32, 1);
  CheckContiguous(arg_dg1, "dg1");
  CheckCudaTensor(arg_dg2, "dg2");
  CheckDtype(arg_dg2, "dg2", 2, 32, 1);
  CheckContiguous(arg_dg2, "dg2");
  CheckCudaTensor(arg_dq_out, "dq_out");
  CheckDtype(arg_dq_out, "dq_out", 4, 16, 1);
  CheckContiguous(arg_dq_out, "dq_out");
  CheckCudaTensor(arg_dk_out, "dk_out");
  CheckDtype(arg_dk_out, "dk_out", 4, 16, 1);
  CheckContiguous(arg_dk_out, "dk_out");
  CheckCudaTensor(arg_dg_out, "dg_out");
  CheckDtype(arg_dg_out, "dg_out", 2, 32, 1);
  CheckContiguous(arg_dg_out, "dg_out");
  CheckCudaTensor(arg_chunk_start, "chunk_start");
  CheckDtype(arg_chunk_start, "chunk_start", 0, 32, 1);
  CheckContiguous(arg_chunk_start, "chunk_start");
  CheckCudaTensor(arg_chunk_len, "chunk_len");
  CheckDtype(arg_chunk_len, "chunk_len", 0, 32, 1);
  CheckContiguous(arg_chunk_len, "chunk_len");
  CAKE_HOST_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_v_heads >= -2147483648LL && arg_num_v_heads <= 2147483647LL, ValueError)
      << "scalar 'num_v_heads' value " << arg_num_v_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_normalize_qk >= -2147483648LL && arg_normalize_qk <= 2147483647LL, ValueError)
      << "scalar 'normalize_qk' value " << arg_normalize_qk
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_kn, arg_qn, "kn", "qn");
  CheckSameCudaDevice(arg_rstd_q, arg_qn, "rstd_q", "qn");
  CheckSameCudaDevice(arg_rstd_k, arg_qn, "rstd_k", "qn");
  CheckSameCudaDevice(arg_dq_hv, arg_qn, "dq_hv", "qn");
  CheckSameCudaDevice(arg_dk_hv, arg_qn, "dk_hv", "qn");
  CheckSameCudaDevice(arg_dk2, arg_qn, "dk2", "qn");
  CheckSameCudaDevice(arg_dg1, arg_qn, "dg1", "qn");
  CheckSameCudaDevice(arg_dg2, arg_qn, "dg2", "qn");
  CheckSameCudaDevice(arg_dq_out, arg_qn, "dq_out", "qn");
  CheckSameCudaDevice(arg_dk_out, arg_qn, "dk_out", "qn");
  CheckSameCudaDevice(arg_dg_out, arg_qn, "dg_out", "qn");
  CheckSameCudaDevice(arg_chunk_start, arg_qn, "chunk_start", "qn");
  CheckSameCudaDevice(arg_chunk_len, arg_qn, "chunk_len", "qn");
  CheckCurrentCudaDevice(arg_qn, "qn");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_qn = static_cast<__nv_bfloat16*>(arg_qn.data_ptr());
  __nv_bfloat16* p_kn = static_cast<__nv_bfloat16*>(arg_kn.data_ptr());
  float* p_rstd_q = static_cast<float*>(arg_rstd_q.data_ptr());
  float* p_rstd_k = static_cast<float*>(arg_rstd_k.data_ptr());
  __nv_bfloat16* p_dq_hv = static_cast<__nv_bfloat16*>(arg_dq_hv.data_ptr());
  __nv_bfloat16* p_dk_hv = static_cast<__nv_bfloat16*>(arg_dk_hv.data_ptr());
  __nv_bfloat16* p_dk2 = static_cast<__nv_bfloat16*>(arg_dk2.data_ptr());
  float* p_dg1 = static_cast<float*>(arg_dg1.data_ptr());
  float* p_dg2 = static_cast<float*>(arg_dg2.data_ptr());
  __nv_bfloat16* p_dq_out = static_cast<__nv_bfloat16*>(arg_dq_out.data_ptr());
  __nv_bfloat16* p_dk_out = static_cast<__nv_bfloat16*>(arg_dk_out.data_ptr());
  float* p_dg_out = static_cast<float*>(arg_dg_out.data_ptr());
  int* p_chunk_start = static_cast<int*>(arg_chunk_start.data_ptr());
  int* p_chunk_len = static_cast<int*>(arg_chunk_len.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int32_t v_num_v_heads = (int32_t)arg_num_v_heads;
  int32_t v_normalize_qk = (int32_t)arg_normalize_qk;
  void* kargs[] = {&p_qn, &p_kn, &p_rstd_q, &p_rstd_k, &p_dq_hv, &p_dk_hv, &p_dk2, &p_dg1, &p_dg2, &p_dq_out, &p_dk_out, &p_dg_out, &p_chunk_start, &p_chunk_len, &v_num_heads, &v_num_v_heads, &v_normalize_qk};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 0u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_7182c463b27a027fca5d), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_gdn_chunk_train_7182c463b27a027fca5d failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_eb0c68226cf71481

CAKE_HOST_STAGE(finalize, cake_host_shim_eb0c68226cf71481::Run);
