/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_gdn_chunk_train_8e5a2923ce82842c7449' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_gdn_chunk_train_8e5a2923ce82842c7449(__nv_bfloat16* __restrict__ qn, __nv_bfloat16* __restrict__ kn, __nv_bfloat16* __restrict__ w, __nv_bfloat16* __restrict__ do_, __nv_bfloat16* __restrict__ dv_local, float* __restrict__ g_cs, float* __restrict__ dht, __nv_bfloat16* __restrict__ dh_out, __nv_bfloat16* __restrict__ dv2, float* __restrict__ dh0, int* __restrict__ chunk_start, int* __restrict__ chunk_len, int* __restrict__ seq_chunk_start, int num_heads, int num_v_heads, int use_final_state_grad, int store_initial_state_grad, float scale);


namespace cake_host_shim_1e431bd5673aed87 {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_qn, TensorView arg_kn, TensorView arg_w, TensorView arg_do, TensorView arg_dv_local, TensorView arg_g_cs, TensorView arg_dht, TensorView arg_dh_out, TensorView arg_dv2, TensorView arg_dh0, TensorView arg_chunk_start, TensorView arg_chunk_len, TensorView arg_seq_chunk_start, int64_t arg_num_heads, int64_t arg_num_v_heads, int64_t arg_use_final_state_grad, int64_t arg_store_initial_state_grad, double arg_scale, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_qn.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_qn, "qn");
  CheckDtype(arg_qn, "qn", 4, 16, 1);
  CheckContiguous(arg_qn, "qn");
  CheckCudaTensor(arg_kn, "kn");
  CheckDtype(arg_kn, "kn", 4, 16, 1);
  CheckContiguous(arg_kn, "kn");
  CheckCudaTensor(arg_w, "w");
  CheckDtype(arg_w, "w", 4, 16, 1);
  CheckContiguous(arg_w, "w");
  CheckCudaTensor(arg_do, "do");
  CheckDtype(arg_do, "do", 4, 16, 1);
  CheckContiguous(arg_do, "do");
  CheckCudaTensor(arg_dv_local, "dv_local");
  CheckDtype(arg_dv_local, "dv_local", 4, 16, 1);
  CheckContiguous(arg_dv_local, "dv_local");
  CheckCudaTensor(arg_g_cs, "g_cs");
  CheckDtype(arg_g_cs, "g_cs", 2, 32, 1);
  CheckContiguous(arg_g_cs, "g_cs");
  CheckCudaTensor(arg_dht, "dht");
  CheckDtype(arg_dht, "dht", 2, 32, 1);
  CheckContiguous(arg_dht, "dht");
  CheckCudaTensor(arg_dh_out, "dh_out");
  CheckDtype(arg_dh_out, "dh_out", 4, 16, 1);
  CheckContiguous(arg_dh_out, "dh_out");
  CheckCudaTensor(arg_dv2, "dv2");
  CheckDtype(arg_dv2, "dv2", 4, 16, 1);
  CheckContiguous(arg_dv2, "dv2");
  CheckCudaTensor(arg_dh0, "dh0");
  CheckDtype(arg_dh0, "dh0", 2, 32, 1);
  CheckContiguous(arg_dh0, "dh0");
  CheckCudaTensor(arg_chunk_start, "chunk_start");
  CheckDtype(arg_chunk_start, "chunk_start", 0, 32, 1);
  CheckContiguous(arg_chunk_start, "chunk_start");
  CheckCudaTensor(arg_chunk_len, "chunk_len");
  CheckDtype(arg_chunk_len, "chunk_len", 0, 32, 1);
  CheckContiguous(arg_chunk_len, "chunk_len");
  CheckCudaTensor(arg_seq_chunk_start, "seq_chunk_start");
  CheckDtype(arg_seq_chunk_start, "seq_chunk_start", 0, 32, 1);
  CheckContiguous(arg_seq_chunk_start, "seq_chunk_start");
  CAKE_HOST_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_v_heads >= -2147483648LL && arg_num_v_heads <= 2147483647LL, ValueError)
      << "scalar 'num_v_heads' value " << arg_num_v_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_use_final_state_grad >= -2147483648LL && arg_use_final_state_grad <= 2147483647LL, ValueError)
      << "scalar 'use_final_state_grad' value " << arg_use_final_state_grad
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_store_initial_state_grad >= -2147483648LL && arg_store_initial_state_grad <= 2147483647LL, ValueError)
      << "scalar 'store_initial_state_grad' value " << arg_store_initial_state_grad
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_kn, arg_qn, "kn", "qn");
  CheckSameCudaDevice(arg_w, arg_qn, "w", "qn");
  CheckSameCudaDevice(arg_do, arg_qn, "do", "qn");
  CheckSameCudaDevice(arg_dv_local, arg_qn, "dv_local", "qn");
  CheckSameCudaDevice(arg_g_cs, arg_qn, "g_cs", "qn");
  CheckSameCudaDevice(arg_dht, arg_qn, "dht", "qn");
  CheckSameCudaDevice(arg_dh_out, arg_qn, "dh_out", "qn");
  CheckSameCudaDevice(arg_dv2, arg_qn, "dv2", "qn");
  CheckSameCudaDevice(arg_dh0, arg_qn, "dh0", "qn");
  CheckSameCudaDevice(arg_chunk_start, arg_qn, "chunk_start", "qn");
  CheckSameCudaDevice(arg_chunk_len, arg_qn, "chunk_len", "qn");
  CheckSameCudaDevice(arg_seq_chunk_start, arg_qn, "seq_chunk_start", "qn");
  CheckCurrentCudaDevice(arg_qn, "qn");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_qn = static_cast<__nv_bfloat16*>(arg_qn.data_ptr());
  __nv_bfloat16* p_kn = static_cast<__nv_bfloat16*>(arg_kn.data_ptr());
  __nv_bfloat16* p_w = static_cast<__nv_bfloat16*>(arg_w.data_ptr());
  __nv_bfloat16* p_do = static_cast<__nv_bfloat16*>(arg_do.data_ptr());
  __nv_bfloat16* p_dv_local = static_cast<__nv_bfloat16*>(arg_dv_local.data_ptr());
  float* p_g_cs = static_cast<float*>(arg_g_cs.data_ptr());
  float* p_dht = static_cast<float*>(arg_dht.data_ptr());
  __nv_bfloat16* p_dh_out = static_cast<__nv_bfloat16*>(arg_dh_out.data_ptr());
  __nv_bfloat16* p_dv2 = static_cast<__nv_bfloat16*>(arg_dv2.data_ptr());
  float* p_dh0 = static_cast<float*>(arg_dh0.data_ptr());
  int* p_chunk_start = static_cast<int*>(arg_chunk_start.data_ptr());
  int* p_chunk_len = static_cast<int*>(arg_chunk_len.data_ptr());
  int* p_seq_chunk_start = static_cast<int*>(arg_seq_chunk_start.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int32_t v_num_v_heads = (int32_t)arg_num_v_heads;
  int32_t v_use_final_state_grad = (int32_t)arg_use_final_state_grad;
  int32_t v_store_initial_state_grad = (int32_t)arg_store_initial_state_grad;
  float v_scale = (float)arg_scale;
  void* kargs[] = {&p_qn, &p_kn, &p_w, &p_do, &p_dv_local, &p_g_cs, &p_dht, &p_dh_out, &p_dv2, &p_dh0, &p_chunk_start, &p_chunk_len, &p_seq_chunk_start, &v_num_heads, &v_num_v_heads, &v_use_final_state_grad, &v_store_initial_state_grad, &v_scale};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_8e5a2923ce82842c7449),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            156672);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  CAKE_HOST_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_gdn_chunk_train_8e5a2923ce82842c7449 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 156672u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_8e5a2923ce82842c7449), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_gdn_chunk_train_8e5a2923ce82842c7449 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_1e431bd5673aed87

CAKE_HOST_STAGE(dhu_r32k2, cake_host_shim_1e431bd5673aed87::Run);
