/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_gdn_chunk_train_cebb1e374d4d4985b293' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_gdn_chunk_train_cebb1e374d4d4985b293(__nv_bfloat16* __restrict__ kn, __nv_bfloat16* __restrict__ w, __nv_bfloat16* __restrict__ u, float* __restrict__ g_cs, float* __restrict__ h0, __nv_bfloat16* __restrict__ h_out, __nv_bfloat16* __restrict__ v_new, float* __restrict__ final_state, int* __restrict__ chunk_start, int* __restrict__ chunk_len, int* __restrict__ seq_chunk_start, int num_heads, int num_v_heads, int use_initial_state, int store_final_state);


namespace cake_host_shim_0a9d8e81db59e0a3 {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_kn, TensorView arg_w, TensorView arg_u, TensorView arg_g_cs, TensorView arg_h0, TensorView arg_h_out, TensorView arg_v_new, TensorView arg_final_state, TensorView arg_chunk_start, TensorView arg_chunk_len, TensorView arg_seq_chunk_start, int64_t arg_num_heads, int64_t arg_num_v_heads, int64_t arg_use_initial_state, int64_t arg_store_final_state, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_kn.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_kn, "kn");
  CheckDtype(arg_kn, "kn", 4, 16, 1);
  CheckContiguous(arg_kn, "kn");
  CheckCudaTensor(arg_w, "w");
  CheckDtype(arg_w, "w", 4, 16, 1);
  CheckContiguous(arg_w, "w");
  CheckCudaTensor(arg_u, "u");
  CheckDtype(arg_u, "u", 4, 16, 1);
  CheckContiguous(arg_u, "u");
  CheckCudaTensor(arg_g_cs, "g_cs");
  CheckDtype(arg_g_cs, "g_cs", 2, 32, 1);
  CheckContiguous(arg_g_cs, "g_cs");
  CheckCudaTensor(arg_h0, "h0");
  CheckDtype(arg_h0, "h0", 2, 32, 1);
  CheckContiguous(arg_h0, "h0");
  CheckCudaTensor(arg_h_out, "h_out");
  CheckDtype(arg_h_out, "h_out", 4, 16, 1);
  CheckContiguous(arg_h_out, "h_out");
  CheckCudaTensor(arg_v_new, "v_new");
  CheckDtype(arg_v_new, "v_new", 4, 16, 1);
  CheckContiguous(arg_v_new, "v_new");
  CheckCudaTensor(arg_final_state, "final_state");
  CheckDtype(arg_final_state, "final_state", 2, 32, 1);
  CheckContiguous(arg_final_state, "final_state");
  CheckCudaTensor(arg_chunk_start, "chunk_start");
  CheckDtype(arg_chunk_start, "chunk_start", 0, 32, 1);
  CheckContiguous(arg_chunk_start, "chunk_start");
  CheckCudaTensor(arg_chunk_len, "chunk_len");
  CheckDtype(arg_chunk_len, "chunk_len", 0, 32, 1);
  CheckContiguous(arg_chunk_len, "chunk_len");
  CheckCudaTensor(arg_seq_chunk_start, "seq_chunk_start");
  CheckDtype(arg_seq_chunk_start, "seq_chunk_start", 0, 32, 1);
  CheckContiguous(arg_seq_chunk_start, "seq_chunk_start");
  CAKE_HOST_CHECK(arg_num_heads >= -2147483648LL && arg_num_heads <= 2147483647LL, ValueError)
      << "scalar 'num_heads' value " << arg_num_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_num_v_heads >= -2147483648LL && arg_num_v_heads <= 2147483647LL, ValueError)
      << "scalar 'num_v_heads' value " << arg_num_v_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_use_initial_state >= -2147483648LL && arg_use_initial_state <= 2147483647LL, ValueError)
      << "scalar 'use_initial_state' value " << arg_use_initial_state
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_store_final_state >= -2147483648LL && arg_store_final_state <= 2147483647LL, ValueError)
      << "scalar 'store_final_state' value " << arg_store_final_state
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_w, arg_kn, "w", "kn");
  CheckSameCudaDevice(arg_u, arg_kn, "u", "kn");
  CheckSameCudaDevice(arg_g_cs, arg_kn, "g_cs", "kn");
  CheckSameCudaDevice(arg_h0, arg_kn, "h0", "kn");
  CheckSameCudaDevice(arg_h_out, arg_kn, "h_out", "kn");
  CheckSameCudaDevice(arg_v_new, arg_kn, "v_new", "kn");
  CheckSameCudaDevice(arg_final_state, arg_kn, "final_state", "kn");
  CheckSameCudaDevice(arg_chunk_start, arg_kn, "chunk_start", "kn");
  CheckSameCudaDevice(arg_chunk_len, arg_kn, "chunk_len", "kn");
  CheckSameCudaDevice(arg_seq_chunk_start, arg_kn, "seq_chunk_start", "kn");
  CheckCurrentCudaDevice(arg_kn, "kn");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_kn = static_cast<__nv_bfloat16*>(arg_kn.data_ptr());
  __nv_bfloat16* p_w = static_cast<__nv_bfloat16*>(arg_w.data_ptr());
  __nv_bfloat16* p_u = static_cast<__nv_bfloat16*>(arg_u.data_ptr());
  float* p_g_cs = static_cast<float*>(arg_g_cs.data_ptr());
  float* p_h0 = static_cast<float*>(arg_h0.data_ptr());
  __nv_bfloat16* p_h_out = static_cast<__nv_bfloat16*>(arg_h_out.data_ptr());
  __nv_bfloat16* p_v_new = static_cast<__nv_bfloat16*>(arg_v_new.data_ptr());
  float* p_final_state = static_cast<float*>(arg_final_state.data_ptr());
  int* p_chunk_start = static_cast<int*>(arg_chunk_start.data_ptr());
  int* p_chunk_len = static_cast<int*>(arg_chunk_len.data_ptr());
  int* p_seq_chunk_start = static_cast<int*>(arg_seq_chunk_start.data_ptr());
  int32_t v_num_heads = (int32_t)arg_num_heads;
  int32_t v_num_v_heads = (int32_t)arg_num_v_heads;
  int32_t v_use_initial_state = (int32_t)arg_use_initial_state;
  int32_t v_store_final_state = (int32_t)arg_store_final_state;
  void* kargs[] = {&p_kn, &p_w, &p_u, &p_g_cs, &p_h0, &p_h_out, &p_v_new, &p_final_state, &p_chunk_start, &p_chunk_len, &p_seq_chunk_start, &v_num_heads, &v_num_v_heads, &v_use_initial_state, &v_store_final_state};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_cebb1e374d4d4985b293),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            98944);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  CAKE_HOST_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_gdn_chunk_train_cebb1e374d4d4985b293 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 98944u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_gdn_chunk_train_cebb1e374d4d4985b293), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_gdn_chunk_train_cebb1e374d4d4985b293 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_0a9d8e81db59e0a3

CAKE_HOST_STAGE(fwd_h_r64k1, cake_host_shim_0a9d8e81db59e0a3::Run);
