"""Shared native-loading support for the kernel packages generated by the Cake compiler.

``csrc/cake_host_shim.h`` is the host surface every generated launcher includes; :mod:`._jit` builds
a package's ``registry.json`` stages into torch CUDA extensions and binds their argument plans.
"""

from ._jit import SUPPORTED_CAPABILITIES, NativeKernel, Package, device_arch

__all__ = ["SUPPORTED_CAPABILITIES", "NativeKernel", "Package", "device_arch"]
