"""
Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
Licensed under the Apache License, Version 2.0.
https://www.apache.org/licenses/LICENSE-2.0

Native loading for the kernel packages generated by the Cake compiler (SM100a / SM103a).

A generated package (``kda_chunk_train``, ``gdn_chunk_train``, ``dsa_train``) is a directory with a
``registry.json`` written mechanically by the kernel generator -- one record per stage with the
argument plan, launch block, dynamic shared memory, the device/launcher source pair under ``csrc/``,
the compile flags and ``arches`` (the architectures the single source set is exported for) -- and the
sources themselves.  The launchers include the shared host surface ``csrc/cake_host_shim.h`` next to
this file.  Each stage builds on first use as a torch CUDA extension for the current device's
architecture (``nvcc`` + ``ninja``; cached per architecture under ``TORCH_EXTENSIONS_DIR``).
"""

import json
import operator
import os
from pathlib import Path

import torch

_CSRC = Path(__file__).resolve().parent / "csrc"
_ARCH_FLAGS = {
    "sm_100a": "-gencode=arch=compute_100a,code=sm_100a",
    "sm_103a": "-gencode=arch=compute_103a,code=sm_103a",
}
SUPPORTED_CAPABILITIES = {(10, 0): "sm_100a", (10, 3): "sm_103a"}
# torch's extension build disables the half / bf16 conversion operators; the generated device code uses them.
_CONVERSION_FLAGS = (
    "-U__CUDA_NO_HALF_OPERATORS__",
    "-U__CUDA_NO_HALF_CONVERSIONS__",
    "-U__CUDA_NO_HALF2_OPERATORS__",
    "-U__CUDA_NO_BFLOAT16_CONVERSIONS__",
)
_DEVICE_ARCH: dict[int, str] = {}


def device_arch(device=None):
    """Map the current CUDA device to the exported architecture tag (cached per device index: the
    capability query costs ~10 us per call and the operators ask once per call)."""
    index = torch.cuda.current_device() if device is None else (device if isinstance(device, int) else device.index)
    if index is None:
        index = torch.cuda.current_device()
    arch = _DEVICE_ARCH.get(index)
    if arch is None:
        capability = torch.cuda.get_device_capability(index)
        try:
            arch = SUPPORTED_CAPABILITIES[capability]
        except KeyError:
            raise NotImplementedError(
                f"the Cake-generated training kernels require SM100a or SM103a, got compute capability {capability}"
            ) from None
        _DEVICE_ARCH[index] = arch
    return arch


class Package:
    """One generated kernel package: its registry and the per-stage native modules.

    ``Package(__file__)`` in the package's host module reads ``registry.json`` next to that file.
    ``env_prefix`` names the package's build environment variables
    (``<env_prefix>_VERBOSE_BUILD``, ``<env_prefix>_PREBUILD``).
    """

    def __init__(self, package_file, env_prefix=None):
        self.root = Path(package_file).resolve().parent
        self.name = self.root.name
        self.env_prefix = env_prefix or f"MILES_{self.name.upper()}"
        registry = self.root / "registry.json"
        # MODULES[stage] -> generated module record; record["arches"] lists the exported architectures.
        self.MODULES = json.loads(registry.read_text()) if registry.is_file() else {}
        self._loaded = {}
        self._kernels = {}

    def record(self, stage, arch):
        record = self.MODULES[stage]
        if arch not in record["arches"]:
            raise NotImplementedError(f"{self.name}/{stage}: not exported for {arch} (exported: {record['arches']})")
        return record

    def stages(self, arch):
        return [stage for stage, record in self.MODULES.items() if arch in record["arches"]]

    def load(self, stage, arch):
        """Build (once per extension cache) and import the native module for ``stage`` on ``arch``."""
        key = (stage, arch)
        native = self._loaded.get(key)
        if native is None:
            from torch.utils.cpp_extension import load as load_extension

            record = self.record(stage, arch)
            native = load_extension(
                name=f"{record['name']}_{arch}",
                sources=[str(self.root / "csrc" / relative) for relative in record["sources"]],
                extra_include_paths=[str(_CSRC)],
                extra_cuda_cflags=[_ARCH_FLAGS[arch], "-O3", *_CONVERSION_FLAGS, *record["compile_flags"]],
                extra_ldflags=["-lcuda"],
                verbose=os.environ.get(f"{self.env_prefix}_VERBOSE_BUILD", "0") == "1",
            )
            self._loaded[key] = native
        return native

    def prebuild(self, arch, max_workers=None):
        """Build every stage for ``arch`` up front, in parallel; return the wall time in seconds.

        Stages otherwise build lazily on first use, so a stage variant first selected mid-training
        would compile inside a training step (about a minute per stage, serially).  Called once by the
        package's operators on their first call on a device; ``<env_prefix>_PREBUILD=0`` disables it.
        """
        import time
        from concurrent.futures import ThreadPoolExecutor

        if os.environ.get(f"{self.env_prefix}_PREBUILD", "1") == "0":
            return 0.0
        stages = self.stages(arch)
        t0 = time.perf_counter()
        workers = max_workers or min(len(stages), max(1, (os.cpu_count() or 8) // 2))
        try:
            with ThreadPoolExecutor(max_workers=workers) as pool:
                list(pool.map(lambda stage: self.load(stage, arch), stages))
        except Exception:  # a concurrent build failure is not fatal: fall back to the serial, cached path
            for stage in stages:
                self.load(stage, arch)
        return time.perf_counter() - t0

    def kernel(self, stage, arch):
        """Return the process-wide NativeKernel for ``stage`` on ``arch``."""
        key = (stage, arch)
        kernel = self._kernels.get(key)
        if kernel is None:
            kernel = self._kernels[key] = NativeKernel(self, stage, arch)
        return kernel


_GRID_AXES = ("grid_x", "grid_y", "grid_z")
# argument-plan segment kinds (see _plan_segments)
_BINDINGS, _GRID, _WORKSPACE = "bindings", "grid", "workspace"


def _is_binding(kind):
    return kind != "grid" and kind != "workspace"


def _bindings_getter(names):
    """``bindings -> tuple of the values of names, in order`` (``itemgetter`` unwraps a single key)."""
    if len(names) == 1:
        (name,) = names

        def single(bindings):
            return (bindings[name],)

        return single
    return operator.itemgetter(*names)


def _plan_segments(arg_plan, descriptor_storage):
    """Compile an exported argument plan into positional segments for :meth:`NativeKernel.launch`.

    Consecutive named entries (buffers, TMA buffers, parameters) collapse into one
    ``(_BINDINGS, getter)`` segment whose getter pulls their values out of the caller's bindings in
    plan order with a single ``itemgetter`` call; ``(_GRID, axis)`` takes one launch-grid component
    and ``(_WORKSPACE, tensor)`` the kernel's fixed descriptor workspace.  The concatenated segments
    reproduce the plan's positional order exactly.
    """
    segments = []
    run = []

    def flush():
        if run:
            segments.append((_BINDINGS, _bindings_getter(tuple(run))))
            run.clear()

    for kind, name in arg_plan:
        if kind == "grid":
            flush()
            segments.append((_GRID, _GRID_AXES.index(name)))
        elif kind == "workspace":
            flush()
            segments.append((_WORKSPACE, descriptor_storage))
        else:
            run.append(name)
    flush()
    return tuple(segments)


class NativeKernel:
    """One generated stage; named bindings are mapped onto the exported argument plan.

    ``launch(grid=(x, y, z), **bindings)`` binds tensors and scalars by their exported names.  The
    caller-owned TMA descriptor workspace (when the stage has one; descriptors are re-encoded on every
    call) and the grid are filled in automatically.  The plan is compiled once here into positional
    segments so a launch costs one set comparison of the binding names and a few ``itemgetter`` calls.
    """

    def __init__(self, package, stage, arch=None, device=None):
        self.package = package
        self.stage = stage
        self.arch = arch or device_arch(device)
        record = package.record(stage, self.arch)
        self.record = record
        native = package.load(stage, self.arch)
        self._call = getattr(native, record["ffi_entry"])
        self._arg_plan = tuple(tuple(item) for item in record["arg_plan"])
        workspace_bytes = int(record["tma_workspace_bytes"])
        self.descriptor_storage = (
            torch.empty(workspace_bytes, dtype=torch.uint8, device=device if device is not None else "cuda")
            if workspace_bytes
            else None
        )
        self._binding_names = frozenset(name for kind, name in self._arg_plan if _is_binding(kind))
        self._segments = _plan_segments(self._arg_plan, self.descriptor_storage)

    def launch(self, *, grid, **bindings):
        if bindings.keys() != self._binding_names:
            self._raise_binding_mismatch(bindings)
        if len(grid) != 3:
            grid = tuple(grid) + (1,) * (3 - len(grid))
        args = []
        for kind, payload in self._segments:
            if kind is _BINDINGS:
                args.extend(payload(bindings))
            elif kind is _GRID:
                args.append(int(grid[payload]))
            else:
                args.append(payload)
        return self._call(*args)

    def _raise_binding_mismatch(self, bindings):
        for kind, name in self._arg_plan:
            if _is_binding(kind) and name not in bindings:
                raise KeyError(f"{self.stage}: missing binding {name!r}")
        unexpected = set(bindings) - self._binding_names
        raise KeyError(f"{self.stage}: unexpected bindings {sorted(unexpected)!r}")
