import os
import sys
from types import ModuleType, SimpleNamespace

import pytest

from miles.utils.tracking_utils import trackio_utils


def _args(**overrides):
    values = {
        "env_report": None,
        "rank": 0,
        "use_trackio": True,
        "wandb_project": "wproj",
        "wandb_group": "wgroup",
        "trackio_project": None,
        "trackio_run_name": None,
        "trackio_run_id": None,
        "trackio_group": None,
        "trackio_space_id": None,
        "trackio_server_url": None,
        "trackio_dir": None,
    }
    values.update(overrides)
    return SimpleNamespace(**values)


class _FakeRun:
    def __init__(self, **kwargs):
        self.kwargs = kwargs
        self.name = kwargs.get("name") or "auto-generated-name"
        self.id = kwargs.get("run_id") or "id-of-" + self.name
        self.log_calls = []
        self.finish_calls = 0

    def log(self, metrics, step=None):
        self.log_calls.append((metrics, step))

    def finish(self):
        self.finish_calls += 1


class _FakeTrackio:
    def __init__(self):
        self.init_calls = []
        self.runs = []
        self.finish_calls = 0

    def init(self, **kwargs):
        self.init_calls.append(kwargs)
        # trackio.init returns a Run; expose .name/.id so the primary can publish
        # the resolved (possibly auto-generated) identity to secondary ranks.
        run = _FakeRun(**kwargs)
        self.runs.append(run)
        return run

    def finish(self):
        self.finish_calls += 1

    @property
    def log_calls(self):
        return [c for run in self.runs for c in run.log_calls]


@pytest.fixture
def fake_trackio(monkeypatch):
    fake = _FakeTrackio()
    # Functions import trackio lazily, so injecting into sys.modules is enough.
    monkeypatch.setitem(sys.modules, "trackio", fake)
    run_module = ModuleType("trackio.run")
    run_module.Run = _FakeRun
    fake.run = run_module
    monkeypatch.setitem(sys.modules, "trackio.run", run_module)
    monkeypatch.setattr(trackio_utils, "_run", None)
    monkeypatch.setattr(trackio_utils, "_run_from_init", False)
    # Avoid leaking TRACKIO_DIR between tests.
    monkeypatch.delenv("TRACKIO_DIR", raising=False)
    monkeypatch.delenv("TRACKIO_SERVER_URL", raising=False)
    monkeypatch.delenv("TRACKIO_SPACE_ID", raising=False)
    return fake


def test_primary_init_starts_run_and_propagates_name(fake_trackio):
    args = _args()
    active = trackio_utils.init_trackio(args, primary=True)

    assert active is True
    assert len(fake_trackio.init_calls) == 1
    call = fake_trackio.init_calls[0]
    # Falls back to wandb naming.
    assert call["project"] == "wproj"
    assert call["name"] == "wgroup"
    assert call["group"] == "wgroup"
    assert call["resume"] == "allow"
    assert isinstance(call["config"], dict)
    # Resolved name propagated for secondary ranks.
    assert args.trackio_run_name == "wgroup"


def test_primary_captures_autogenerated_name_when_unset(fake_trackio):
    # Neither trackio-run-name nor wandb-group set -> name resolves to None and
    # trackio auto-generates one; the primary must propagate that resolved name
    # so secondary ranks attach to the same run.
    args = _args(wandb_group=None, trackio_run_name=None)
    trackio_utils.init_trackio(args, primary=True)

    assert fake_trackio.init_calls[0]["name"] is None
    assert args.trackio_run_name == "auto-generated-name"


def test_trackio_overrides_take_precedence(fake_trackio):
    args = _args(trackio_project="tproj", trackio_run_name="trun", trackio_group="tgrp")
    trackio_utils.init_trackio(args, primary=True)

    call = fake_trackio.init_calls[0]
    assert call["project"] == "tproj"
    assert call["name"] == "trun"
    assert call["group"] == "tgrp"


def test_secondary_remote_attaches_to_same_run(fake_trackio):
    args = _args(trackio_server_url="http://host:7860", trackio_run_name="wgroup")
    active = trackio_utils.init_trackio(args, primary=False)

    assert active is True
    call = fake_trackio.init_calls[0]
    assert call["name"] == "wgroup"
    assert call["server_url"] == "http://host:7860"
    assert call["resume"] == "allow"


def test_secondary_local_opens_run_by_id_without_init(fake_trackio):
    # Actors and rollout_manager init with primary=False. resume="allow" only
    # matches a run that has already logged, so a name-based attach would mint a
    # second run id; the secondary opens the primary's run id directly instead.
    args = _args(trackio_run_name="from-primary", trackio_run_id="run-123")

    assert trackio_utils.init_trackio(args, primary=False) is True
    assert fake_trackio.init_calls == []
    run = trackio_utils._run
    assert run.kwargs == {
        "url": None,
        "project": "wproj",
        "client": None,
        "name": "from-primary",
        "run_id": "run-123",
        "group": "wgroup",
    }

    trackio_utils.log_metrics({"rollout/reward": 1.0})
    trackio_utils.finish()

    assert run.log_calls == [({"rollout/reward": 1.0}, None)]
    assert run.finish_calls == 1
    assert fake_trackio.finish_calls == 0


def test_primary_publishes_run_id(fake_trackio):
    args = _args()

    trackio_utils.init_trackio(args, primary=True)

    assert args.trackio_run_id == "id-of-wgroup"


def test_disabled_returns_false_and_clears_run_name(fake_trackio):
    args = _args(use_trackio=False, trackio_run_name="stale")
    active = trackio_utils.init_trackio(args, primary=True)

    assert active is False
    assert args.trackio_run_name is None
    assert fake_trackio.init_calls == []


def _install_import_probe(monkeypatch, seen: dict):
    # Replace the fake module with an import hook so the test observes the
    # environment at the moment ``import trackio`` executes.
    import importlib.abc
    import importlib.util

    class _Loader(importlib.abc.Loader):
        def create_module(self, spec):
            return None

        def exec_module(self, module):
            seen["TRACKIO_DIR"] = os.environ.get("TRACKIO_DIR")
            module.init = lambda **kwargs: SimpleNamespace(name=kwargs.get("name"))

    class _Finder(importlib.abc.MetaPathFinder):
        def find_spec(self, fullname, path, target=None):
            if fullname == "trackio":
                return importlib.util.spec_from_loader(fullname, _Loader())
            return None

    monkeypatch.delitem(sys.modules, "trackio", raising=False)
    monkeypatch.setattr(sys, "meta_path", [_Finder(), *sys.meta_path])


@pytest.mark.parametrize("primary", [True, False])
def test_trackio_dir_is_exported_before_trackio_import(fake_trackio, monkeypatch, tmp_path, primary):
    # trackio resolves TRACKIO_DIR once at import time, so setting it after the
    # import would silently ignore --trackio-dir.
    seen = {}
    _install_import_probe(monkeypatch, seen)
    target = tmp_path / "trackio-logs"

    trackio_utils.init_trackio(_args(trackio_dir=str(target), trackio_run_name="r"), primary=primary)

    assert seen["TRACKIO_DIR"] == str(target)
    assert target.is_dir()


def test_trackio_dir_not_exported_for_remote(fake_trackio, monkeypatch, tmp_path):
    args = _args(trackio_dir=str(tmp_path / "ignored"), trackio_server_url="http://tracker:7860")

    trackio_utils.init_trackio(args, primary=True)

    assert "TRACKIO_DIR" not in os.environ
    assert not (tmp_path / "ignored").exists()


def test_log_and_finish_delegate(fake_trackio):
    trackio_utils.init_trackio(_args(), primary=True)

    trackio_utils.log_metrics({"train/loss": 0.5, "train/step": 3}, step=3)
    trackio_utils.finish()

    assert fake_trackio.log_calls == [({"train/loss": 0.5, "train/step": 3}, None)]
    # A run opened by trackio.init is closed through trackio.finish, which also
    # clears trackio's current-run context so its atexit hook does not finish twice.
    assert fake_trackio.finish_calls == 1
    assert fake_trackio.runs[0].finish_calls == 0
    assert trackio_utils._run is None


def test_backend_inactive_skips_log_and_finish(fake_trackio):
    from miles.utils.tracking_utils.base import TrackioBackend

    backend = TrackioBackend()
    args = _args(use_trackio=False)
    backend.init(args, primary=True)

    backend.log({"a": 1}, step=1)
    backend.finish()

    assert fake_trackio.log_calls == []
    assert fake_trackio.finish_calls == 0


def test_registry_lifecycle_through_tracking_manager(fake_trackio):
    from miles.utils.tracking_utils.base import TrackingManager, TrackioBackend

    manager = TrackingManager({"trackio": (TrackioBackend, "use_trackio")})
    args = _args(trackio_run_name="lifecycle")

    manager.init(args, primary=False)
    run = trackio_utils._run
    manager.log({"train/loss": 0.25}, step=7)
    manager.finish()

    assert fake_trackio.init_calls == []
    assert run.kwargs["name"] == "lifecycle"
    assert run.log_calls == [({"train/loss": 0.25}, None)]
    assert run.finish_calls == 1
