/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_dsa_train_bfcdd38b8b2b9195ae2f' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_dsa_train_bfcdd38b8b2b9195ae2f(__nv_bfloat16* __restrict__ index_q, __nv_bfloat16* __restrict__ index_k, float* __restrict__ weights, int* __restrict__ topk_indices, float* __restrict__ grad_scores, __nv_bfloat16* __restrict__ d_index_q, float* __restrict__ d_weights, float* __restrict__ partial, int heads, int topk);


namespace cake_host_shim_917b2d501264ca8a {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_index_q, TensorView arg_index_k, TensorView arg_weights, TensorView arg_topk_indices, TensorView arg_grad_scores, TensorView arg_d_index_q, TensorView arg_d_weights, TensorView arg_partial, int64_t arg_heads, int64_t arg_topk, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_index_q.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_index_q, "index_q");
  CheckDtype(arg_index_q, "index_q", 4, 16, 1);
  CheckContiguous(arg_index_q, "index_q");
  CheckCudaTensor(arg_index_k, "index_k");
  CheckDtype(arg_index_k, "index_k", 4, 16, 1);
  CheckContiguous(arg_index_k, "index_k");
  CheckCudaTensor(arg_weights, "weights");
  CheckDtype(arg_weights, "weights", 2, 32, 1);
  CheckContiguous(arg_weights, "weights");
  CheckCudaTensor(arg_topk_indices, "topk_indices");
  CheckDtype(arg_topk_indices, "topk_indices", 0, 32, 1);
  CheckContiguous(arg_topk_indices, "topk_indices");
  CheckCudaTensor(arg_grad_scores, "grad_scores");
  CheckDtype(arg_grad_scores, "grad_scores", 2, 32, 1);
  CheckContiguous(arg_grad_scores, "grad_scores");
  CheckCudaTensor(arg_d_index_q, "d_index_q");
  CheckDtype(arg_d_index_q, "d_index_q", 4, 16, 1);
  CheckContiguous(arg_d_index_q, "d_index_q");
  CheckCudaTensor(arg_d_weights, "d_weights");
  CheckDtype(arg_d_weights, "d_weights", 2, 32, 1);
  CheckContiguous(arg_d_weights, "d_weights");
  CheckCudaTensor(arg_partial, "partial");
  CheckDtype(arg_partial, "partial", 2, 32, 1);
  CheckContiguous(arg_partial, "partial");
  CAKE_HOST_CHECK(arg_heads >= -2147483648LL && arg_heads <= 2147483647LL, ValueError)
      << "scalar 'heads' value " << arg_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_topk >= -2147483648LL && arg_topk <= 2147483647LL, ValueError)
      << "scalar 'topk' value " << arg_topk
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_index_k, arg_index_q, "index_k", "index_q");
  CheckSameCudaDevice(arg_weights, arg_index_q, "weights", "index_q");
  CheckSameCudaDevice(arg_topk_indices, arg_index_q, "topk_indices", "index_q");
  CheckSameCudaDevice(arg_grad_scores, arg_index_q, "grad_scores", "index_q");
  CheckSameCudaDevice(arg_d_index_q, arg_index_q, "d_index_q", "index_q");
  CheckSameCudaDevice(arg_d_weights, arg_index_q, "d_weights", "index_q");
  CheckSameCudaDevice(arg_partial, arg_index_q, "partial", "index_q");
  CheckCurrentCudaDevice(arg_index_q, "index_q");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_index_q = static_cast<__nv_bfloat16*>(arg_index_q.data_ptr());
  __nv_bfloat16* p_index_k = static_cast<__nv_bfloat16*>(arg_index_k.data_ptr());
  float* p_weights = static_cast<float*>(arg_weights.data_ptr());
  int* p_topk_indices = static_cast<int*>(arg_topk_indices.data_ptr());
  float* p_grad_scores = static_cast<float*>(arg_grad_scores.data_ptr());
  __nv_bfloat16* p_d_index_q = static_cast<__nv_bfloat16*>(arg_d_index_q.data_ptr());
  float* p_d_weights = static_cast<float*>(arg_d_weights.data_ptr());
  float* p_partial = static_cast<float*>(arg_partial.data_ptr());
  int32_t v_heads = (int32_t)arg_heads;
  int32_t v_topk = (int32_t)arg_topk;
  void* kargs[] = {&p_index_q, &p_index_k, &p_weights, &p_topk_indices, &p_grad_scores, &p_d_index_q, &p_d_weights, &p_partial, &v_heads, &v_topk};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 33664u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_dsa_train_bfcdd38b8b2b9195ae2f), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_dsa_train_bfcdd38b8b2b9195ae2f failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_917b2d501264ca8a

CAKE_HOST_STAGE(dsa_indexer_bwd_h32, cake_host_shim_917b2d501264ca8a::Run);
