/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_dsa_train_0e5bfc20af4ca8061522' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_dsa_train_0e5bfc20af4ca8061522(__nv_bfloat16* __restrict__ index_q, __nv_bfloat16* __restrict__ index_k, float* __restrict__ weights, int* __restrict__ cu_ks, int* __restrict__ cu_ke, float* __restrict__ logits, int seq_len, int seq_len_kv);


namespace cake_host_shim_90c0d95a3f281d2e {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_index_q, TensorView arg_index_k, TensorView arg_weights, TensorView arg_cu_ks, TensorView arg_cu_ke, TensorView arg_logits, int64_t arg_seq_len, int64_t arg_seq_len_kv, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_index_q.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_index_q, "index_q");
  CheckDtype(arg_index_q, "index_q", 4, 16, 1);
  CheckContiguous(arg_index_q, "index_q");
  CheckCudaTensor(arg_index_k, "index_k");
  CheckDtype(arg_index_k, "index_k", 4, 16, 1);
  CheckContiguous(arg_index_k, "index_k");
  CheckCudaTensor(arg_weights, "weights");
  CheckDtype(arg_weights, "weights", 2, 32, 1);
  CheckContiguous(arg_weights, "weights");
  CheckCudaTensor(arg_cu_ks, "cu_ks");
  CheckDtype(arg_cu_ks, "cu_ks", 0, 32, 1);
  CheckContiguous(arg_cu_ks, "cu_ks");
  CheckCudaTensor(arg_cu_ke, "cu_ke");
  CheckDtype(arg_cu_ke, "cu_ke", 0, 32, 1);
  CheckContiguous(arg_cu_ke, "cu_ke");
  CheckCudaTensor(arg_logits, "logits");
  CheckDtype(arg_logits, "logits", 2, 32, 1);
  CheckContiguous(arg_logits, "logits");
  CAKE_HOST_CHECK(arg_seq_len >= -2147483648LL && arg_seq_len <= 2147483647LL, ValueError)
      << "scalar 'seq_len' value " << arg_seq_len
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_seq_len_kv >= -2147483648LL && arg_seq_len_kv <= 2147483647LL, ValueError)
      << "scalar 'seq_len_kv' value " << arg_seq_len_kv
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_index_k, arg_index_q, "index_k", "index_q");
  CheckSameCudaDevice(arg_weights, arg_index_q, "weights", "index_q");
  CheckSameCudaDevice(arg_cu_ks, arg_index_q, "cu_ks", "index_q");
  CheckSameCudaDevice(arg_cu_ke, arg_index_q, "cu_ke", "index_q");
  CheckSameCudaDevice(arg_logits, arg_index_q, "logits", "index_q");
  CheckCurrentCudaDevice(arg_index_q, "index_q");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_index_q = static_cast<__nv_bfloat16*>(arg_index_q.data_ptr());
  __nv_bfloat16* p_index_k = static_cast<__nv_bfloat16*>(arg_index_k.data_ptr());
  float* p_weights = static_cast<float*>(arg_weights.data_ptr());
  int* p_cu_ks = static_cast<int*>(arg_cu_ks.data_ptr());
  int* p_cu_ke = static_cast<int*>(arg_cu_ke.data_ptr());
  float* p_logits = static_cast<float*>(arg_logits.data_ptr());
  int32_t v_seq_len = (int32_t)arg_seq_len;
  int32_t v_seq_len_kv = (int32_t)arg_seq_len_kv;
  void* kargs[] = {&p_index_q, &p_index_k, &p_weights, &p_cu_ks, &p_cu_ke, &p_logits, &v_seq_len, &v_seq_len_kv};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_dsa_train_0e5bfc20af4ca8061522),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            82176);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  CAKE_HOST_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_dsa_train_0e5bfc20af4ca8061522 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(256u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 82176u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_dsa_train_0e5bfc20af4ca8061522), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_dsa_train_0e5bfc20af4ca8061522 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_90c0d95a3f281d2e

CAKE_HOST_STAGE(dsa_indexer_logits_h64, cake_host_shim_90c0d95a3f281d2e::Run);
