/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_dsa_train_e8ed07f283c6a1c4d5ad' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_dsa_train_e8ed07f283c6a1c4d5ad(float* __restrict__ logits, int* __restrict__ cu_ks, int* __restrict__ cu_ke, int seq_len, int seq_len_kv);


namespace cake_host_shim_e3e1af846253f86f {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_logits, TensorView arg_cu_ks, TensorView arg_cu_ke, int64_t arg_seq_len, int64_t arg_seq_len_kv, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_logits.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_logits, "logits");
  CheckDtype(arg_logits, "logits", 2, 32, 1);
  CheckContiguous(arg_logits, "logits");
  CheckCudaTensor(arg_cu_ks, "cu_ks");
  CheckDtype(arg_cu_ks, "cu_ks", 0, 32, 1);
  CheckContiguous(arg_cu_ks, "cu_ks");
  CheckCudaTensor(arg_cu_ke, "cu_ke");
  CheckDtype(arg_cu_ke, "cu_ke", 0, 32, 1);
  CheckContiguous(arg_cu_ke, "cu_ke");
  CAKE_HOST_CHECK(arg_seq_len >= -2147483648LL && arg_seq_len <= 2147483647LL, ValueError)
      << "scalar 'seq_len' value " << arg_seq_len
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_seq_len_kv >= -2147483648LL && arg_seq_len_kv <= 2147483647LL, ValueError)
      << "scalar 'seq_len_kv' value " << arg_seq_len_kv
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_cu_ks, arg_logits, "cu_ks", "logits");
  CheckSameCudaDevice(arg_cu_ke, arg_logits, "cu_ke", "logits");
  CheckCurrentCudaDevice(arg_logits, "logits");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  float* p_logits = static_cast<float*>(arg_logits.data_ptr());
  int* p_cu_ks = static_cast<int*>(arg_cu_ks.data_ptr());
  int* p_cu_ke = static_cast<int*>(arg_cu_ke.data_ptr());
  int32_t v_seq_len = (int32_t)arg_seq_len;
  int32_t v_seq_len_kv = (int32_t)arg_seq_len_kv;
  void* kargs[] = {&p_logits, &p_cu_ks, &p_cu_ke, &v_seq_len, &v_seq_len_kv};


  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(256u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 0u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_dsa_train_e8ed07f283c6a1c4d5ad), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_dsa_train_e8ed07f283c6a1c4d5ad failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_e3e1af846253f86f

CAKE_HOST_STAGE(dsa_indexer_clean, cake_host_shim_e3e1af846253f86f::Run);
