/*
 * Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Cake source exporter — do not edit.
// Torch host-shim launcher for Cake kernel 'kernel_cake_dsa_train_804ac6b172f9ab6cb741' (host surface: cake_host_shim.h).
#include <cuda.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>

#include "cake_host_shim.h"

#include <atomic>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

extern "C" __global__ void kernel_cake_dsa_train_804ac6b172f9ab6cb741(__nv_bfloat16* __restrict__ q, __nv_bfloat16* __restrict__ kv, float* __restrict__ sink, int* __restrict__ indices, __nv_bfloat16* __restrict__ out, float* __restrict__ lse, int heads, int topk, float scale_log2);


namespace cake_host_shim_7eb61d0e1f0c4920 {

// ScopedCudaDevice and the argument checks are shipped once in cake_host_shim.h.
using namespace ::cake_host;

void Run(TensorView arg_q, TensorView arg_kv, TensorView arg_sink, TensorView arg_indices, TensorView arg_out, TensorView arg_lse, int64_t arg_heads, int64_t arg_topk, double arg_scale_log2, int64_t grid_x, int64_t grid_y, int64_t grid_z) {
  DLDevice dev = arg_q.device();
  ScopedCudaDevice device_guard(dev.device_id);
  CheckCudaTensor(arg_q, "q");
  CheckDtype(arg_q, "q", 4, 16, 1);
  CheckContiguous(arg_q, "q");
  CheckCudaTensor(arg_kv, "kv");
  CheckDtype(arg_kv, "kv", 4, 16, 1);
  CheckContiguous(arg_kv, "kv");
  CheckCudaTensor(arg_sink, "sink");
  CheckDtype(arg_sink, "sink", 2, 32, 1);
  CheckContiguous(arg_sink, "sink");
  CheckCudaTensor(arg_indices, "indices");
  CheckDtype(arg_indices, "indices", 0, 32, 1);
  CheckContiguous(arg_indices, "indices");
  CheckCudaTensor(arg_out, "out");
  CheckDtype(arg_out, "out", 4, 16, 1);
  CheckContiguous(arg_out, "out");
  CheckCudaTensor(arg_lse, "lse");
  CheckDtype(arg_lse, "lse", 2, 32, 1);
  CheckContiguous(arg_lse, "lse");
  CAKE_HOST_CHECK(arg_heads >= -2147483648LL && arg_heads <= 2147483647LL, ValueError)
      << "scalar 'heads' value " << arg_heads
      << " is outside i32 range [-2147483648, 2147483647]";
  CAKE_HOST_CHECK(arg_topk >= -2147483648LL && arg_topk <= 2147483647LL, ValueError)
      << "scalar 'topk' value " << arg_topk
      << " is outside i32 range [-2147483648, 2147483647]";
  CheckSameCudaDevice(arg_kv, arg_q, "kv", "q");
  CheckSameCudaDevice(arg_sink, arg_q, "sink", "q");
  CheckSameCudaDevice(arg_indices, arg_q, "indices", "q");
  CheckSameCudaDevice(arg_out, arg_q, "out", "q");
  CheckSameCudaDevice(arg_lse, arg_q, "lse", "q");
  CheckCurrentCudaDevice(arg_q, "q");
  CAKE_HOST_CHECK(grid_x > 0 && grid_y > 0 && grid_z > 0, ValueError)
      << "launch grid dimensions must be positive, got (" << grid_x << ", " << grid_y
      << ", " << grid_z << ")";

  cudaStream_t stream = (cudaStream_t)::cake_host::CurrentStream(dev.device_type, dev.device_id);
  __nv_bfloat16* p_q = static_cast<__nv_bfloat16*>(arg_q.data_ptr());
  __nv_bfloat16* p_kv = static_cast<__nv_bfloat16*>(arg_kv.data_ptr());
  float* p_sink = static_cast<float*>(arg_sink.data_ptr());
  int* p_indices = static_cast<int*>(arg_indices.data_ptr());
  __nv_bfloat16* p_out = static_cast<__nv_bfloat16*>(arg_out.data_ptr());
  float* p_lse = static_cast<float*>(arg_lse.data_ptr());
  int32_t v_heads = (int32_t)arg_heads;
  int32_t v_topk = (int32_t)arg_topk;
  float v_scale_log2 = (float)arg_scale_log2;
  void* kargs[] = {&p_q, &p_kv, &p_sink, &p_indices, &p_out, &p_lse, &v_heads, &v_topk, &v_scale_log2};

  static std::mutex smem_mu;
  static auto* smem_status_by_device =
      new std::unordered_map<int, cudaError_t>();
  cudaError_t smem_status = cudaSuccess;
  {
    std::lock_guard<std::mutex> lock(smem_mu);
    auto it = smem_status_by_device->find(dev.device_id);
    if (it == smem_status_by_device->end()) {
      int current_device = -1;
      smem_status = cudaGetDevice(&current_device);
      if (smem_status == cudaSuccess && current_device != dev.device_id) {
        smem_status = cudaErrorInvalidDevice;
      }
      if (smem_status == cudaSuccess) {
        smem_status = cudaFuncSetAttribute(
            reinterpret_cast<const void*>(kernel_cake_dsa_train_804ac6b172f9ab6cb741),
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            168960);
      }
      smem_status_by_device->emplace(dev.device_id, smem_status);
    } else {
      smem_status = it->second;
    }
  }
  CAKE_HOST_CHECK(smem_status == cudaSuccess, RuntimeError)
      << "cudaFuncSetAttribute for kernel_cake_dsa_train_804ac6b172f9ab6cb741 failed: "
      << cudaGetErrorString(smem_status);
  dim3 grid((uint32_t)grid_x, (uint32_t)grid_y, (uint32_t)grid_z);
  dim3 block(128u, 1u, 1u);

  cudaLaunchConfig_t config{};
  config.gridDim = grid;
  config.blockDim = block;
  config.dynamicSmemBytes = 168960u;
  config.stream = stream;
  cudaError_t launch_status = cudaLaunchKernelExC(
      &config, reinterpret_cast<const void*>(kernel_cake_dsa_train_804ac6b172f9ab6cb741), kargs);
  CAKE_HOST_CHECK(launch_status == cudaSuccess, RuntimeError)
      << "cudaLaunchKernelExC for kernel_cake_dsa_train_804ac6b172f9ab6cb741 failed: "
      << cudaGetErrorString(launch_status);
}

}  // namespace cake_host_shim_7eb61d0e1f0c4920

CAKE_HOST_STAGE(dsa_attention_fwd_h16_d512t64, cake_host_shim_7eb61d0e1f0c4920::Run);
