"""NVIDIA XID codes that require GPU reset, node reboot, or hardware replacement.

Auto-generated from Xid-Catalog.xlsx by converter.py.
Source: https://docs.nvidia.com/deploy/xid-errors/Xid-Catalog.xlsx
"""

FATAL_XIDS: frozenset[int] = frozenset({
    46,  # ROBUST_CHANNEL_GPU_TIMEOUT_ERROR, RESET_GPU
    48,  # ROBUST_CHANNEL_GPU_ECC_DBE, WORKFLOW_XID_48
    62,  # PMU_HALT_ERROR, RESET_GPU
    64,  # INFOROM_DRAM_RETIREMENT_FAILURE, RESET_GPU
    74,  # NVLINK_ERROR, WORKFLOW_NVLINK_ERR
    79,  # ROBUST_CHANNEL_GPU_HAS_FALLEN_OFF_THE_BUS, RESTART_BM
    95,  # ROBUST_CHANNEL_UNCONTAINED_ERROR, RESET_GPU
    109,  # ROBUST_CHANNEL_CTXSW_TIMEOUT_ERROR, RESET_GPU
    110,  # SEC_FAULT_ERROR, RESET_GPU
    119,  # GSP_RPC_TIMEOUT, RESET_GPU
    120,  # GSP_ERROR, RESET_GPU
    136,  # ALI_TRAINING_FAIL, RESET_GPU
    140,  # UNRECOVERABLE_ECC_ERROR_ESCAPE, RESET_GPU
    143,  # GPU_INIT_ERROR, RESET_GPU
    144,  # NVLINK_SAW_ERROR, WORKFLOW_NVLINK5_ERR
    145,  # NVLINK_RLW_ERROR, WORKFLOW_NVLINK5_ERR
    146,  # NVLINK_TLW_ERROR, WORKFLOW_NVLINK5_ERR
    147,  # NVLINK_TREX_ERROR, WORKFLOW_NVLINK5_ERR
    148,  # NVLINK_NVLPW_CTRL_ERROR, WORKFLOW_NVLINK5_ERR
    149,  # NVLINK_NETIR_ERROR, WORKFLOW_NVLINK5_ERR
    150,  # NVLINK_MSE_ERROR, WORKFLOW_NVLINK5_ERR
    155,  # NVLINK_SW_DEFINED_ERROR, RESET_GPU
    156,  # RESOURCE_RETIREMENT_EVENT, RESET_GPU
    158,  # GPU_FATAL_TIMEOUT, RESET_GPU
})
