"""Deterministic chunked KDA training backward for Blackwell (SM100a / SM103a).

Generated by the Cake compiler from the flash-linear-attention v0.5.2 ``chunk_kda`` dataflow
(in-kernel Q/K L2 normalization, lower-bound safe gate, sigmoid beta, ``dt_bias``; chunk 64,
K = V = 128): ten backward stages with fp32 inter-chunk state carriers, bf16 hand-offs at the
reference's rounding points and fixed-order reductions without atomics, so repeated backward
passes on identical inputs are bit-identical. :func:`chunk_kda_backward` consumes the chunked
forward's saved set; the forward itself stays in flash-linear-attention. :func:`chunk_kda` is the
fla ``chunk_kda`` drop-in that pairs the two, which ``--kda-backend deterministic`` selects.
"""

from ._jit import SUPPORTED_CAPABILITIES, device_arch
from .backward import chunk_kda_backward
from .kda_backend import chunk_kda, deterministic_backward_applies

__all__ = [
    "SUPPORTED_CAPABILITIES",
    "chunk_kda",
    "chunk_kda_backward",
    "deterministic_backward_applies",
    "device_arch",
]
