"""Deterministic chunked KDA training backward for Blackwell (SM100a / SM103a).

Generated by the Cake compiler from the flash-linear-attention v0.5.2 ``chunk_kda`` dataflow
(in-kernel Q/K L2 normalization, lower-bound safe gate, sigmoid beta, ``dt_bias``; chunk 64,
K = V = 128): ten backward stages with fp32 inter-chunk state carriers, bf16 hand-offs at the
reference's rounding points and fixed-order reductions without atomics, so repeated backward
passes on identical inputs are bit-identical. :func:`chunk_kda_backward` consumes the chunked
forward's saved set; the forward itself stays in flash-linear-attention.
"""

from ..cake_native import SUPPORTED_CAPABILITIES, device_arch
from .backward import chunk_kda_backward

__all__ = ["SUPPORTED_CAPABILITIES", "chunk_kda_backward", "device_arch"]
